const $=id=>document.getElementById(id);
const CONFIG=window.KHADAMATI_CONFIG||{};
const BACKEND_READY=Boolean(CONFIG.supabaseUrl&&CONFIG.supabaseAnonKey&&window.supabase);
const sb=BACKEND_READY?window.supabase.createClient(CONFIG.supabaseUrl,CONFIG.supabaseAnonKey):null;
let sessionUser=null, selectedService='', selectedProvider=null, profileProvider=null, selectedRating=0, appliedCoupon=null;

const serviceInfo={'الاستعلامات':['🔎','الاستعلامات','استعلم عن حالة طلب أو معاملة وسجّل التفاصيل التي تريد متابعتها.'],'المدفوعات':['💳','المدفوعات','سجّل طلب مساعدة بخصوص فاتورة أو دفعة إلكترونية.'],'الطلبات':['📋','الطلبات','أنشئ طلب خدمة جديد وتابع حالته.'],'الخدمات الحكومية':['🏛️','الخدمات الحكومية','واجهة موحدة لاستقبال طلبات الخدمات الحكومية المتاحة لاحقاً عبر API.'],'الشكاوى':['📝','الشكاوى','قدّم شكوى مع وصف المشكلة ليتم تسجيلها ومتابعتها.'],'المساعدة':['💬','المساعدة والدعم','أرسل استفسارك أو المشكلة التي تواجهها وسجّلها كطلب دعم.']};
const publicServices={
 inquiries:{title:'الاستعلامات',icon:'🔎',desc:'استعلم عن حالة طلب أو معاملة وتابع التفاصيل بسهولة.'},
 payments:{title:'المدفوعات',icon:'💳',desc:'مساعدة في الفواتير والمدفوعات الإلكترونية ومتابعة العمليات.'},
 requests:{title:'الطلبات',icon:'📋',desc:'أنشئ طلب خدمة وتابع تنفيذه من مكان واحد.'},
 government:{title:'الخدمات الحكومية',icon:'🏛️',desc:'واجهة موحدة للوصول إلى الخدمات الحكومية المتاحة.'},
 complaints:{title:'الشكاوى',icon:'📝',desc:'قدّم شكوى وتابع حالتها والرد عليها.'},
 support:{title:'المساعدة والدعم',icon:'💬',desc:'احصل على المساعدة وسجّل مشكلة أو استفسار.'}
};
function updateSEO(title,desc){document.title=title+' | خدماتي';let m=document.querySelector('meta[name="description"]');if(m)m.setAttribute('content',desc);let og=document.querySelector('meta[property="og:title"]');if(og)og.setAttribute('content',title+' | خدماتي');let od=document.querySelector('meta[property="og:description"]');if(od)od.setAttribute('content',desc);}
function openPublicService(slug){const x=publicServices[slug];if(!x)return;trackEvent('service_view','service:'+slug);show('servicePage');$('publicServiceTitle').textContent=x.title;$('publicServiceIcon').textContent=x.icon;$('publicServiceDesc').textContent=x.desc;$('publicServiceLongDesc').textContent=x.desc+' يمكنك البدء بطلب الخدمة الآن، ثم متابعة الحالة والتواصل مع مقدم الخدمة من داخل المنصة.';updateSEO(x.title,x.desc);location.hash='service='+encodeURIComponent(slug);$('publicServiceRequestBtn').onclick=()=>{if(!user())return show('loginPage');openServiceModal(x.title)};$('serviceBackBtn').onclick=()=>{history.pushState({},'',location.pathname+location.search);updateSEO('خدماتي','خدماتي منصة عربية لطلب الخدمات، اكتشاف مقدمي الخدمات ومتابعة الطلبات بأمان.');showHome()};$('relatedServices').innerHTML=Object.entries(publicServices).filter(([k])=>k!==slug).slice(0,4).map(([k,v])=>`<button class="related-service" data-slug="${k}">${v.icon} ${escapeHtml(v.title)}</button>`).join('');document.querySelectorAll('.related-service').forEach(b=>b.onclick=()=>openPublicService(b.dataset.slug));}

function validPhone(p){return /^01[0-9]{9}$/.test(p)}
function setMsg(id,t,ok=false){const e=$(id);if(!e)return;e.textContent=t;e.classList.toggle('success-msg',ok)}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function show(page){['publicPage','loginPage','signupPage','homePage','providersPage','providerProfilePage','requestsPage','adminPage','walletPage','chatPage','servicePage'].forEach(id=>$(id)?.classList.add('hidden'));$(page)?.classList.remove('hidden');$('logoutTop')?.classList.toggle('hidden',!['homePage','requestsPage','adminPage'].includes(page))}
function demoUser(){try{return JSON.parse(localStorage.getItem('khadamatiDemoUser')||'null')}catch{return null}}
function saveDemoUser(u){localStorage.setItem('khadamatiDemoUser',JSON.stringify(u))}
function clearDemo(){localStorage.removeItem('khadamatiDemoUser')}
function currentDemo(){const u=demoUser();return u?{id:'demo',name:u.name,phone:u.phone,role:u.role||'user'}:null}
const defaultProviders=[{id:'demo-p1',name:'أحمد للتصميم',category:'تصميم',description:'تصميم بوستات وهوية بصرية بشكل احترافي.',price:150,contact:'01011111111'},{id:'demo-p2',name:'تسويق أونلاين',category:'تسويق',description:'إدارة صفحات وإعلانات ممولة وخطة تسويق.',price:200,contact:'01022222222'},{id:'demo-p3',name:'محمود للبرمجة',category:'برمجة',description:'إنشاء مواقع وصفحات هبوط وتعديل المواقع.',price:300,contact:'01033333333'}];
function demoProviders(){try{return JSON.parse(localStorage.getItem('khadamatiProviders')||'null')||defaultProviders}catch{return defaultProviders}}
function saveProviders(a){localStorage.setItem('khadamatiProviders',JSON.stringify(a))}
function user(){return BACKEND_READY?sessionUser:currentDemo()}
function statusClass(s){return s==='تم التنفيذ'?'done':s==='جاري التنفيذ'?'working':s==='ملغي'?'cancelled':'pending'}
function formatDate(v){try{return new Intl.DateTimeFormat('ar-EG',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch{return v}}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}

async function trackEvent(eventType,page,metadata={}){try{if(BACKEND_READY&&sessionUser)await sb.from('platform_events').insert({user_id:sessionUser.id,event_type:eventType,page,metadata});}catch{}}
const notificationIcons={request:'📋',status:'🔄',payment:'💳',earning:'📈',refund:'↩️',system:'🔔'};
function demoNotifications(){try{return JSON.parse(localStorage.getItem('khadamatiNotifications')||'[]')}catch{return []}}
function saveDemoNotifications(a){localStorage.setItem('khadamatiNotifications',JSON.stringify(a.slice(0,100)))}
function addDemoNotification(title,body,type='system'){const a=demoNotifications();a.unshift({id:'dn-'+Date.now()+'-'+Math.random().toString(16).slice(2),title,body,type,read:false,created_at:new Date().toISOString()});saveDemoNotifications(a);renderNotifications()}
async function loadNotifications(){
  if(!BACKEND_READY) return demoNotifications();
  const {data,error}=await sb.from('notifications').select('id,title,body,type,read,created_at').order('created_at',{ascending:false}).limit(50);
  if(error) throw error; return data||[];
}
function notificationHtml(n){const icon=notificationIcons[n.type]||'🔔';return `<article class="notification-item ${n.read?'':'unread'}" data-notification-id="${escapeHtml(n.id)}"><span class="notification-icon">${icon}</span><div><b>${escapeHtml(n.title)}</b><p>${escapeHtml(n.body)}</p><small>${formatDate(n.created_at||n.createdAt)}</small>${n.read?'':'<div class="notification-actions"><button class="secondary mark-one" data-id="'+escapeHtml(n.id)+'">تحديد كمقروء</button></div>'}</div></article>`}
async function renderNotifications(){
  if(!user()) return;
  try{const list=await loadNotifications(); const unread=list.filter(n=>!n.read).length;
    $('notificationsCount').textContent=unread; $('notifDot').style.display=unread?'block':'none'; $('notifBadge').textContent=unread; $('notifBadge').classList.toggle('hidden',!unread);
    const home=$('notificationsList'); if(home) home.innerHTML=list.length?list.slice(0,5).map(notificationHtml).join(''):'<div class="notification-empty"><div>🔔</div>لا توجد إشعارات جديدة.</div>';
    const modal=$('notificationsModalList'); if(modal) modal.innerHTML=list.length?list.map(notificationHtml).join(''):'<div class="notification-empty"><div>🔔</div>لا توجد إشعارات.</div>';
    document.querySelectorAll('.mark-one').forEach(b=>b.onclick=()=>markNotificationRead(b.dataset.id));
  }catch(e){if($('notificationsList'))$('notificationsList').innerHTML='<div class="notification-empty">تعذر تحميل الإشعارات حالياً.</div>'}
}
async function markNotificationRead(id){try{async function showPublic(){show('publicPage');try{const list=await loadProviders();const top=list.slice(0,3);$('publicProvidersList').innerHTML=top.length?top.map(p=>`<article class="provider-card"><div class="provider-avatar">🧑‍💼</div><span class="provider-category">${escapeHtml(p.category)}</span><h3>${escapeHtml(p.name)}</h3><p class="provider-desc">${escapeHtml(p.description)}</p><div class="provider-price">${escapeHtml(p.price)} جنيه <small>يبدأ من</small></div><div class="provider-actions"><button class="secondary public-profile" data-id="${escapeHtml(p.id)}">عرض الملف</button></div></article>`).join(''):'<div class="empty-state"><div>🧑‍💼</div><h3>لا يوجد مقدمو خدمات بعد</h3><p>كن أول من يضيف خدمته.</p></div>';document.querySelectorAll('.public-profile').forEach(b=>b.onclick=()=>showProviderProfile(b.dataset.id))}catch(e){$('publicProvidersList').innerHTML='<div class="empty-state"><h3>تعذر تحميل مقدمي الخدمات</h3></div>'}}
$('publicProvidersBtn')?.addEventListener('click',showProviders);$('publicSeeAll')?.addEventListener('click',showProviders);$('publicLoginBtn')?.addEventListener('click',()=>show('loginPage'));document.querySelectorAll('.service[data-service-slug]').forEach(b=>b.addEventListener('click',()=>openPublicService(b.dataset.serviceSlug)));

function handlePublicHash(){const sm=location.hash.match(/^#service=(.+)$/);if(sm){openPublicService(decodeURIComponent(sm[1]));return true}const m=location.hash.match(/^#provider=(.+)$/);if(m){showProviderProfile(decodeURIComponent(m[1]));return true}return false}
if(BACKEND_READY){const {error}=await sb.from('notifications').update({read:true}).eq('id',id).eq('user_id',sessionUser.id);if(error)throw error}else{const a=demoNotifications();const n=a.find(x=>String(x.id)===String(id));if(n)n.read=true;saveDemoNotifications(a)}renderNotifications()}catch(e){toast('تعذر تحديث الإشعار')}}
async function markAllNotificationsRead(){try{async function showPublic(){show('publicPage');try{const list=await loadProviders();const top=list.slice(0,3);$('publicProvidersList').innerHTML=top.length?top.map(p=>`<article class="provider-card"><div class="provider-avatar">🧑‍💼</div><span class="provider-category">${escapeHtml(p.category)}</span><h3>${escapeHtml(p.name)}</h3><p class="provider-desc">${escapeHtml(p.description)}</p><div class="provider-price">${escapeHtml(p.price)} جنيه <small>يبدأ من</small></div><div class="provider-actions"><button class="secondary public-profile" data-id="${escapeHtml(p.id)}">عرض الملف</button></div></article>`).join(''):'<div class="empty-state"><div>🧑‍💼</div><h3>لا يوجد مقدمو خدمات بعد</h3><p>كن أول من يضيف خدمته.</p></div>';document.querySelectorAll('.public-profile').forEach(b=>b.onclick=()=>showProviderProfile(b.dataset.id))}catch(e){$('publicProvidersList').innerHTML='<div class="empty-state"><h3>تعذر تحميل مقدمي الخدمات</h3></div>'}}
$('publicProvidersBtn')?.addEventListener('click',showProviders);$('publicSeeAll')?.addEventListener('click',showProviders);$('publicLoginBtn')?.addEventListener('click',()=>show('loginPage'));document.querySelectorAll('.service[data-service-slug]').forEach(b=>b.addEventListener('click',()=>openPublicService(b.dataset.serviceSlug)));

function handlePublicHash(){const sm=location.hash.match(/^#service=(.+)$/);if(sm){openPublicService(decodeURIComponent(sm[1]));return true}const m=location.hash.match(/^#provider=(.+)$/);if(m){showProviderProfile(decodeURIComponent(m[1]));return true}return false}
if(BACKEND_READY){const {error}=await sb.from('notifications').update({read:true}).eq('user_id',sessionUser.id).eq('read',false);if(error)throw error}else{const a=demoNotifications().map(x=>({...x,read:true}));saveDemoNotifications(a)}toast('تمت قراءة كل الإشعارات ✓');renderNotifications()}catch(e){toast('تعذر تحديث الإشعارات')}}
function openNotifications(){if(!user())return show('loginPage');$('notificationsModal').classList.remove('hidden');$('notificationsModal').setAttribute('aria-hidden','false');renderNotifications()}
function closeNotifications(){$('notificationsModal').classList.add('hidden');$('notificationsModal').setAttribute('aria-hidden','true')}
function seedDemoNotifications(){if(!BACKEND_READY&&!localStorage.getItem('khadamatiNotifications')){saveDemoNotifications([{id:'welcome-1',title:'مرحباً بك في خدماتي',body:'يمكنك الآن استكشاف الخدمات ومقدمي الخدمات من مكان واحد.',type:'system',read:false,created_at:new Date().toISOString()},{id:'secure-1',title:'نظام الوساطة جاهز',body:'يتم حجز مبلغ الطلب حتى تأكيد استلام الخدمة.',type:'payment',read:false,created_at:new Date(Date.now()-60000).toISOString()}])}}
function subscribeNotifications(){if(!BACKEND_READY||!sessionUser)return null;return sb.channel('khadamati-notifications-'+sessionUser.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:'user_id=eq.'+sessionUser.id},payload=>{toast('🔔 '+(payload.new?.title||'لديك إشعار جديد'));renderNotifications()}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'notifications',filter:'user_id=eq.'+sessionUser.id},()=>renderNotifications()).subscribe()}
let notificationChannel=null;

async function loadProfile(){if(!BACKEND_READY)return currentDemo();const {data:{user:u}}=await sb.auth.getUser();if(!u)return null;const {data:p,error}=await sb.from('profiles').select('id,full_name,phone,role').eq('id',u.id).single();if(error)throw error;sessionUser={id:p.id,name:p.full_name,phone:p.phone,role:p.role};return sessionUser}
async function loadRequests(){if(!BACKEND_READY){return demoUser()?.requestList||[]}const {data,error}=await sb.from('service_requests').select('id,service,note,status,created_at,provider_id,provider_price,platform_fee,payment_status,provider_net').order('created_at',{ascending:false});if(error)throw error;return data.map(r=>({...r,createdAt:r.created_at,providerId:r.provider_id,providerPrice:r.provider_price,platformFee:r.platform_fee,paymentStatus:r.payment_status,providerNet:r.provider_net}))}
async function createRequest(service,note,providerId=null){if(!BACKEND_READY){const u=demoUser()||{name:'أحمد',phone:'01000000000',role:'user'};u.requestList=u.requestList||[];const p=providerId?demoProviders().find(x=>String(x.id)===String(providerId)):null;const r={id:'KHD-'+Date.now().toString().slice(-6),service,note,providerId,providerName:p?.name||'',providerPrice:p?.price||0,platformFee:p?Number(p.price)*0.10:0,providerNet:p?Number(p.price)*0.90:0,paymentStatus:p?'pending':'not_required',createdAt:new Date().toISOString(),status:'قيد المراجعة',rated:false};u.requestList.unshift(r);saveDemoUser(u);trackEvent('request_created','request:'+r.id,{service,provider_id:providerId});addDemoNotification('تم إنشاء طلب جديد','تم تسجيل طلبك '+r.id+' بنجاح.','request');return r}const p=providerId?await getProvider(providerId):null;const price=p?.price||null;const fee=p?Number(price)*Number(p.commission_rate||10)/100:0;const {data,error}=await sb.from('service_requests').insert({user_id:sessionUser.id,service,note,provider_id:providerId||null,provider_price:price,platform_fee:fee,provider_net:p?Number(price)-fee:0,payment_status:p?'pending':'not_required'}).select('id,service,note,status,created_at,provider_id,provider_price,platform_fee,provider_net,payment_status').single();if(error)throw error;trackEvent('request_created','request:'+data.id,{service,provider_id:providerId});return data}
async function showHome(){const u=user();if(!u)return show('loginPage');show('homePage');$('welcomeName').textContent=u.name||'بك';try{const list=await loadRequests();$('requestsCount').textContent=list.length;renderRequestsPreview(list);updateWalletMini();renderNotifications()}catch(e){toast('تعذر تحميل الطلبات')} }
async function showRequests(){const u=user();if(!u)return show('loginPage');show('requestsPage');try{renderRequests(await loadRequests())}catch(e){setMsg('requestPageMsg','تعذر تحميل الطلبات حالياً.')}}
function renderRequests(list){const box=$('requestsList');$('requestsPageCount').textContent=list.length;if(!list.length){box.innerHTML='<div class="empty-state"><div>📋</div><h3>لا توجد طلبات حتى الآن</h3><p>ابدأ من الخدمات الرئيسية وأنشئ أول طلب لك.</p><button class="primary" id="emptyHomeBtn">استكشاف الخدمات</button></div>';$('emptyHomeBtn').onclick=showHome;return}box.innerHTML=list.map(r=>`<article class="request-card"><div class="request-top"><span class="request-id">${escapeHtml(r.id)}</span><span class="status ${statusClass(r.status)}">${escapeHtml(r.status||'قيد المراجعة')}</span></div><div class="request-service">${serviceInfo[r.service]?.[0]||'📋'} <b>${escapeHtml(r.service)}</b></div><p>${escapeHtml(r.note)}</p><small>${formatDate(r.createdAt)}</small>${r.paymentStatus==='held'?`<div class="escrow-note">🔐 المبلغ محجوز حتى تأكيد استلامك للخدمة.</div><button class="primary release-payment" data-request='${escapeHtml(JSON.stringify(r))}' ${r.status!=='تم التنفيذ'?'disabled':''}>${r.status==='تم التنفيذ'?'✅ تأكيد استلام الخدمة':'⏳ بانتظار اكتمال الخدمة'}</button>`:''}${r.paymentStatus==='released'?`<div class="escrow-note success-msg">✅ تم تحرير المبلغ لمقدم الخدمة.</div>`:''}${r.paymentStatus==='refunded'?`<div class="escrow-note success-msg">↩️ تم استرداد المبلغ إلى محفظتك.</div>`:''}${r.providerId?`<button class="secondary chat-request" data-request='${escapeHtml(JSON.stringify(r))}'>💬 محادثة مع مقدم الخدمة</button>`:''}${r.providerId&&r.status==='تم التنفيذ'&&!r.rated?`<button class="secondary rate-request" data-request='${escapeHtml(JSON.stringify(r))}'>⭐ قيّم مقدم الخدمة</button>`:''}</article>`).join('');bindRatingButtons()}
function bindRatingButtons(){document.querySelectorAll('.rate-request').forEach(b=>b.onclick=()=>openRatingForRequest(JSON.parse(b.dataset.request)));document.querySelectorAll('.release-payment').forEach(b=>b.onclick=()=>releasePayment(JSON.parse(b.dataset.request)));document.querySelectorAll('.chat-request').forEach(b=>b.onclick=()=>openChat(JSON.parse(b.dataset.request)))}
function renderRequestsPreview(list){const box=$('requestsPreview');if(!list.length){box.innerHTML='<p class="muted">لا توجد طلبات بعد. ابدأ باختيار خدمة من الأعلى.</p>';return}box.innerHTML=list.slice(0,3).map(r=>`<div class="mini-request"><span>${serviceInfo[r.service]?.[0]||'📋'}</span><div><b>${escapeHtml(r.service)}</b><small>${escapeHtml(r.status||'قيد المراجعة')} · ${formatDate(r.createdAt)}</small></div></div>`).join('')}

let activeChatRequest=null, chatChannel=null;
function demoChats(){try{return JSON.parse(localStorage.getItem('khadamatiChats')||'{}')}catch{return {}}}
function saveDemoChats(x){localStorage.setItem('khadamatiChats',JSON.stringify(x))}
function chatKey(rid){return String(rid)}
function chatBubble(m){const mine=BACKEND_READY?m.sender_id===sessionUser?.id:m.sender_id==='me';return `<div class="chat-row ${mine?'mine':'theirs'}"><div class="chat-bubble"><p>${escapeHtml(m.body)}</p><small>${formatDate(m.created_at||m.createdAt)}</small></div></div>`}
async function loadChatMessages(requestId){
  if(!BACKEND_READY){const all=demoChats();return all[chatKey(requestId)]||[]}
  const {data,error}=await sb.from('service_messages').select('id,request_id,sender_id,receiver_id,body,created_at').eq('request_id',Number(requestId)).order('created_at',{ascending:true});
  if(error)throw error;return data||[]
}
async function renderChat(){if(!activeChatRequest)return;try{const list=await loadChatMessages(activeChatRequest.id);$('chatMessages').innerHTML=list.length?list.map(chatBubble).join(''):'<div class="chat-empty">💬<b>ابدأ المحادثة</b><span>اكتب تفاصيل أو أسئلة تخص هذا الطلب.</span></div>';$('chatMessages').scrollTop=$('chatMessages').scrollHeight}catch(e){$('chatMessages').innerHTML='<div class="chat-empty">تعذر تحميل الرسائل حالياً.</div>'}}
async function sendChatMessage(){const body=$('chatInput').value.trim();if(!activeChatRequest||!body)return setMsg('chatMsg','اكتب رسالة أولاً.');try{if(!BACKEND_READY){const all=demoChats(),k=chatKey(activeChatRequest.id),arr=all[k]||[];arr.push({id:'m-'+Date.now(),sender_id:'me',receiver_id:'provider',body,createdAt:new Date().toISOString()});all[k]=arr;saveDemoChats(all);addDemoNotification('رسالة جديدة','تم إرسال رسالة في طلب '+activeChatRequest.id+'.','system')}else{const {data:p,error:pe}=await sb.from('providers').select('user_id,name').eq('id',Number(activeChatRequest.providerId)).single();if(pe)throw pe;const {error}=await sb.from('service_messages').insert({request_id:Number(activeChatRequest.id),sender_id:sessionUser.id,receiver_id:p.user_id,body});if(error)throw error} $('chatInput').value='';setMsg('chatMsg','تم إرسال الرسالة ✓',true);await renderChat()}catch(e){setMsg('chatMsg','تعذر إرسال الرسالة حالياً. '+(e.message||''))}}
async function openChat(r){if(!user())return show('loginPage');if(!r?.providerId)return toast('لا توجد محادثة لهذا الطلب');activeChatRequest=r;show('chatPage');$('chatTitle').textContent='طلب '+r.id;$('chatSubtitle').textContent=(r.providerName||'مقدم الخدمة')+' · '+r.service;$('chatInput').value='';setMsg('chatMsg','');await renderChat();if(chatChannel&&BACKEND_READY)sb.removeChannel(chatChannel);async function showPublic(){show('publicPage');try{const list=await loadProviders();const top=list.slice(0,3);$('publicProvidersList').innerHTML=top.length?top.map(p=>`<article class="provider-card"><div class="provider-avatar">🧑‍💼</div><span class="provider-category">${escapeHtml(p.category)}</span><h3>${escapeHtml(p.name)}</h3><p class="provider-desc">${escapeHtml(p.description)}</p><div class="provider-price">${escapeHtml(p.price)} جنيه <small>يبدأ من</small></div><div class="provider-actions"><button class="secondary public-profile" data-id="${escapeHtml(p.id)}">عرض الملف</button></div></article>`).join(''):'<div class="empty-state"><div>🧑‍💼</div><h3>لا يوجد مقدمو خدمات بعد</h3><p>كن أول من يضيف خدمته.</p></div>';document.querySelectorAll('.public-profile').forEach(b=>b.onclick=()=>showProviderProfile(b.dataset.id))}catch(e){$('publicProvidersList').innerHTML='<div class="empty-state"><h3>تعذر تحميل مقدمي الخدمات</h3></div>'}}
$('publicProvidersBtn')?.addEventListener('click',showProviders);$('publicSeeAll')?.addEventListener('click',showProviders);$('publicLoginBtn')?.addEventListener('click',()=>show('loginPage'));document.querySelectorAll('.service[data-service-slug]').forEach(b=>b.addEventListener('click',()=>openPublicService(b.dataset.serviceSlug)));

function handlePublicHash(){const sm=location.hash.match(/^#service=(.+)$/);if(sm){openPublicService(decodeURIComponent(sm[1]));return true}const m=location.hash.match(/^#provider=(.+)$/);if(m){showProviderProfile(decodeURIComponent(m[1]));return true}return false}
if(BACKEND_READY){chatChannel=sb.channel('chat-'+r.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'service_messages',filter:'request_id=eq.'+r.id},()=>renderChat()).subscribe()}}
function closeChat(){if(chatChannel&&BACKEND_READY){sb.removeChannel(chatChannel);chatChannel=null}activeChatRequest=null}

async function walletData(){
  if(!BACKEND_READY){const u=demoUser()||{};const tx=JSON.parse(localStorage.getItem('khadamatiWalletTx')||'[]');const providers=demoProviders().filter(p=>p.userId==='demo'||p.contact===u.phone);const req=u.requestList||[];const spent=req.filter(r=>['held','released'].includes(r.paymentStatus)).reduce((a,r)=>a+Number(r.providerPrice||0),0);const earned=req.filter(r=>['held','released'].includes(r.paymentStatus)&&r.status==='تم التنفيذ').reduce((a,r)=>a+Number(r.providerNet||0),0);const fees=req.filter(r=>['held','released'].includes(r.paymentStatus)).reduce((a,r)=>a+Number(r.platformFee||0),0);return {balance:Number(u.walletBalance||0),spent,earned,fees,tx}}
  const {data:acc,error}=await sb.from('wallet_accounts').select('balance').eq('user_id',sessionUser.id).maybeSingle();if(error)throw error;
  const {data:tx,error:te}=await sb.from('wallet_transactions').select('id,type,amount,note,created_at').eq('user_id',sessionUser.id).order('created_at',{ascending:false}).limit(30);if(te)throw te;
  const {data:req,error:re}=await sb.from('service_requests').select('provider_id,provider_price,platform_fee,provider_net,payment_status,status,providers!inner(user_id)').eq('providers.user_id',sessionUser.id);
  if(re) throw re; const mine=req||[];return {balance:Number(acc?.balance||0),spent:mine.filter(x=>['held','released'].includes(x.payment_status)&&x.status!=='تم التنفيذ').reduce((a,x)=>a+Number(x.provider_price||0),0),earned:mine.filter(x=>x.payment_status==='released'&&x.status==='تم التنفيذ').reduce((a,x)=>a+Number(x.provider_net||0),0),fees:mine.filter(x=>['held','released'].includes(x.payment_status)).reduce((a,x)=>a+Number(x.platform_fee||0),0),tx:tx||[]};
}
function money(n){return Number(n||0).toFixed(2)+' جنيه'}
async function renderWallet(){if(!user())return show('loginPage');show('walletPage');try{const w=await walletData();$('walletBalance').textContent=money(w.balance);$('walletPageBalance').textContent=money(w.balance);$('walletSpent').textContent=money(w.spent);$('walletEarned').textContent=money(w.earned);$('walletFees').textContent=money(w.fees);$('walletTransactions').innerHTML=w.tx.length?w.tx.map(t=>`<div class=\"wallet-tx\"><span>${t.type==='deposit'?'➕':t.type==='payment'?'💳':t.type==='earning'?'📈':'🏦'}</span><div><b>${escapeHtml(t.note||t.type)}</b><small>${formatDate(t.created_at||t.createdAt)}</small></div><strong>${Number(t.amount)>=0?'+':''}${money(t.amount)}</strong></div>`).join(''):'<div class=\"empty-state\"><div>💸</div><h3>لا توجد عمليات</h3><p>استخدم الشحن التجريبي لبدء المحاكاة.</p></div>'}catch(e){toast('تعذر تحميل المحفظة')}}
async function addDemoBalance(){async function showPublic(){show('publicPage');try{const list=await loadProviders();const top=list.slice(0,3);$('publicProvidersList').innerHTML=top.length?top.map(p=>`<article class="provider-card"><div class="provider-avatar">🧑‍💼</div><span class="provider-category">${escapeHtml(p.category)}</span><h3>${escapeHtml(p.name)}</h3><p class="provider-desc">${escapeHtml(p.description)}</p><div class="provider-price">${escapeHtml(p.price)} جنيه <small>يبدأ من</small></div><div class="provider-actions"><button class="secondary public-profile" data-id="${escapeHtml(p.id)}">عرض الملف</button></div></article>`).join(''):'<div class="empty-state"><div>🧑‍💼</div><h3>لا يوجد مقدمو خدمات بعد</h3><p>كن أول من يضيف خدمته.</p></div>';document.querySelectorAll('.public-profile').forEach(b=>b.onclick=()=>showProviderProfile(b.dataset.id))}catch(e){$('publicProvidersList').innerHTML='<div class="empty-state"><h3>تعذر تحميل مقدمي الخدمات</h3></div>'}}
$('publicProvidersBtn')?.addEventListener('click',showProviders);$('publicSeeAll')?.addEventListener('click',showProviders);$('publicLoginBtn')?.addEventListener('click',()=>show('loginPage'));document.querySelectorAll('.service[data-service-slug]').forEach(b=>b.addEventListener('click',()=>openPublicService(b.dataset.serviceSlug)));

function handlePublicHash(){const sm=location.hash.match(/^#service=(.+)$/);if(sm){openPublicService(decodeURIComponent(sm[1]));return true}const m=location.hash.match(/^#provider=(.+)$/);if(m){showProviderProfile(decodeURIComponent(m[1]));return true}return false}
if(BACKEND_READY){toast('الشحن الحقيقي يحتاج بوابة دفع مرتبطة.');return}const u=demoUser();u.walletBalance=Number(u.walletBalance||0)+500;saveDemoUser(u);const tx=JSON.parse(localStorage.getItem('khadamatiWalletTx')||'[]');tx.unshift({type:'deposit',amount:500,note:'شحن تجريبي',createdAt:new Date().toISOString()});localStorage.setItem('khadamatiWalletTx',JSON.stringify(tx));toast('تمت إضافة 500 جنيه تجريبياً');renderWallet();updateWalletMini()}
let pendingPayment=null;function openCheckout(request){appliedCoupon=null;const price=Number(request.providerPrice||0),fee=Number(request.platformFee||price*0.10),total=price+fee;pendingPayment={...request,total};$('checkoutTitle').textContent='طلب '+request.id+' — '+(request.providerName||'مقدم الخدمة');$('checkoutPrice').textContent=money(price);$('checkoutFee').textContent=money(fee);$('checkoutTotal').textContent=money(total);$('couponCode').value='';$('couponDiscountRow').classList.add('hidden');setMsg('couponMsg','');setMsg('checkoutMsg','');$('checkoutModal').classList.remove('hidden');$('checkoutModal').setAttribute('aria-hidden','false')}
const COUPONS={KHADAMATI10:{type:'percent',value:10,min:100,maxDiscount:100},WELCOME50:{type:'fixed',value:50,min:300,maxDiscount:50}};
async function applyCoupon(){const code=($('couponCode')?.value||'').trim().toUpperCase();if(!pendingPayment)return;let c=null;if(BACKEND_READY){try{const {data,error}=await sb.rpc('validate_coupon',{p_code:code,p_amount:Number(pendingPayment.providerPrice||0)});if(!error&&data?.length)c=data[0]}catch{}}else{c=COUPONS[code];if(c)c={code,type:c.type,value:c.value,min_amount:c.min,max_discount:c.maxDiscount,discount:c.type==='percent'?Math.min(Number(pendingPayment.providerPrice||0)*c.value/100,c.maxDiscount):Math.min(c.value,Number(pendingPayment.providerPrice||0))}}if(!c)return appliedCoupon=null,$('couponDiscountRow').classList.add('hidden'),setMsg('couponMsg','كود الخصم غير صحيح أو منتهي.');if(c.min_amount&&Number(pendingPayment.providerPrice||0)<Number(c.min_amount))return appliedCoupon=null,setMsg('couponMsg',`الحد الأدنى لهذا الكود ${c.min_amount} جنيه.`);const discount=Number(c.discount||0);appliedCoupon={code,discount};$('checkoutDiscount').textContent=money(discount);$('couponDiscountRow').classList.remove('hidden');setMsg('couponMsg',`تم تطبيق الخصم: ${money(discount)} ✓`,true);updateCheckoutTotal()}
function updateCheckoutTotal(){if(!pendingPayment)return;const price=Number(pendingPayment.providerPrice||0),fee=Number(pendingPayment.platformFee||0),discount=Number(appliedCoupon?.discount||0),total=Math.max(0,price+fee-discount);$('checkoutFee').textContent=money(fee);$('checkoutTotal').textContent=money(total);pendingPayment.total=total}
async function payPending(){if(!pendingPayment)return;try{if(!BACKEND_READY){const u=demoUser();const bal=Number(u.walletBalance||0);if(bal<pendingPayment.total)return setMsg('checkoutMsg','الرصيد غير كافٍ. افتح المحفظة واشحن رصيداً تجريبياً.');u.walletBalance=bal-pendingPayment.total;const r=(u.requestList||[]).find(x=>String(x.id)===String(pendingPayment.id));if(r)r.paymentStatus='held';saveDemoUser(u);const tx=JSON.parse(localStorage.getItem('khadamatiWalletTx')||'[]');tx.unshift({type:'payment',amount:-pendingPayment.total,note:'حجز مبلغ الطلب في الوساطة '+pendingPayment.id,createdAt:new Date().toISOString()});localStorage.setItem('khadamatiWalletTx',JSON.stringify(tx))}else{const {error}=await sb.rpc('pay_for_request',{p_request_id:Number(pendingPayment.id)});if(error)throw error}setMsg('checkoutMsg','تم الدفع بنجاح ✅',true);toast('تم تأكيد الدفع');setTimeout(()=>{closeCheckout();showRequests();updateWalletMini()},600)}catch(e){setMsg('checkoutMsg','تعذر تنفيذ الدفع. '+(e.message||''))}}
async function releasePayment(request){try{if(!request||request.status!=='تم التنفيذ')return toast('لا يمكن تأكيد الاستلام قبل اكتمال الطلب');if(request.paymentStatus==='released')return toast('تم تحرير المبلغ بالفعل');if(request.paymentStatus!=='held')return toast('لا يوجد مبلغ محجوز لهذا الطلب');if(!BACKEND_READY){const u=demoUser();const r=(u.requestList||[]).find(x=>String(x.id)===String(request.id));if(r){r.paymentStatus='released';const net=Number(r.providerNet||Math.max(Number(r.providerPrice||0)-Number(r.platformFee||0),0));const tx=JSON.parse(localStorage.getItem('khadamatiWalletTx')||'[]');tx.unshift({type:'earning',amount:net,note:'تحرير أرباح الطلب '+request.id,createdAt:new Date().toISOString()});localStorage.setItem('khadamatiWalletTx',JSON.stringify(tx));saveDemoUser(u)}}else{const {error}=await sb.rpc('release_request_payment',{p_request_id:Number(request.id)});if(error)throw error}toast('تم تأكيد الاستلام وتحرير المبلغ ✅');await showRequests();}catch(e){toast('تعذر تحرير المبلغ: '+(e.message||''))}}
function closeCheckout(){pendingPayment=null;$('checkoutModal').classList.add('hidden');$('checkoutModal').setAttribute('aria-hidden','true')}
async function updateWalletMini(){if(!user()||!$('walletBalance'))return;try{const w=await walletData();$('walletBalance').textContent=money(w.balance)}catch{}}
$('loginBtn').onclick=async()=>{const p=$('phone').value.trim(),pass=$('password').value;if(!validPhone(p))return setMsg('loginMsg','اكتب رقم هاتف مصري صحيح من 11 رقم.');if(!BACKEND_READY){const u=demoUser();if(!u)return setMsg('loginMsg','لا يوجد حساب تجريبي محفوظ. أنشئ حساباً أولاً.');if(u.phone!==p||u.password!==pass)return setMsg('loginMsg','رقم الهاتف أو كلمة السر غير صحيحة.');return showHome()}setMsg('loginMsg','جاري تسجيل الدخول...');const email=`${p}@khadamati.local`;const {error}=await sb.auth.signInWithPassword({email,password:pass});if(error)return setMsg('loginMsg','تعذر تسجيل الدخول. تأكد من البيانات أو الحساب.');try{await loadProfile();setMsg('loginMsg','');showHome()}catch(e){setMsg('loginMsg','تم الدخول لكن تعذر تحميل الملف الشخصي.')}};
$('demoBtn').onclick=()=>{saveDemoUser({name:'أحمد',phone:'01000000000',password:'123456',role:'user',walletBalance:1000,requestList:[{id:'KHD-1001',service:'الطلبات',note:'طلب تجريبي محفوظ',createdAt:new Date().toISOString(),status:'قيد المراجعة'}]});showHome()};
$('logoutTop').onclick=async()=>{if(BACKEND_READY)await sb.auth.signOut();sessionUser=null;clearDemo();show('loginPage')};
$('signupBtn').onclick=()=>{setMsg('loginMsg','');show('signupPage');$('signupName').focus()};$('backLoginBtn').onclick=()=>{setMsg('signupMsg','');show('loginPage')};
$('createAccountBtn').onclick=async()=>{const n=$('signupName').value.trim(),p=$('signupPhone').value.trim(),a=$('signupPassword').value,b=$('signupPassword2').value;if(n.length<2)return setMsg('signupMsg','اكتب اسمك بالكامل.');if(!validPhone(p))return setMsg('signupMsg','اكتب رقم هاتف مصري صحيح من 11 رقم.');if(a.length<6)return setMsg('signupMsg','كلمة السر يجب أن تكون 6 أحرف أو أرقام على الأقل.');if(a!==b)return setMsg('signupMsg','كلمتا السر غير متطابقتين.');if(!BACKEND_READY){saveDemoUser({name:n,phone:p,password:a,role:'user',requestList:[]});setMsg('signupMsg','تم إنشاء الحساب التجريبي بنجاح ✅',true);return setTimeout(showHome,450)}setMsg('signupMsg','جاري إنشاء الحساب...');const email=`${p}@khadamati.local`;const {data,error}=await sb.auth.signUp({email,password:a});if(error)return setMsg('signupMsg','تعذر إنشاء الحساب: '+error.message);if(!data.user)return setMsg('signupMsg','تعذر إنشاء الحساب.');const {error:pe}=await sb.from('profiles').insert({id:data.user.id,full_name:n,phone:p,role:'user'});if(pe)return setMsg('signupMsg','تم إنشاء الحساب لكن تعذر حفظ الملف الشخصي.');await loadProfile();setMsg('signupMsg','تم إنشاء الحساب بنجاح ✅',true);setTimeout(showHome,500)};
$('forgotBtn').onclick=()=>setMsg('loginMsg',BACKEND_READY?'استعادة كلمة السر تحتاج بريد/هاتف استرجاع حقيقي في إعدادات مزود المصادقة.':'في الوضع التجريبي لا توجد استعادة كلمة سر حقيقية.');
$('togglePass').onclick=()=>{const f=$('password'),s=f.type==='text';f.type=s?'password':'text';$('togglePass').textContent=s?'◉':'◎'};

async function getProvider(id){const list=await loadProviders();return list.find(x=>String(x.id)===String(id))||null}
async function providerStats(id){if(!BACKEND_READY){const all=demoUser()?.requestList||[];const completed=all.filter(r=>String(r.providerId)===String(id)&&r.status==='تم التنفيذ').length;const ratings=JSON.parse(localStorage.getItem('khadamatiRatings')||'[]').filter(r=>String(r.providerId)===String(id));return {completed,ratings}}const {data,error}=await sb.rpc('get_provider_stats',{p_provider_id:Number(id)});if(error)throw error;const row=(data||[])[0]||{completed:0,reviews:0,average:0};const {data:ratings,error:re}=await sb.from('provider_reviews').select('rating,comment,created_at,profiles(full_name)').eq('provider_id',id).order('created_at',{ascending:false});if(re)throw re;return {completed:Number(row.completed||0),ratings:ratings||[],average:Number(row.average||0)}}
async function showProviderProfile(id){const p=await getProvider(id);if(!p)return toast('مقدم الخدمة غير موجود');trackEvent('provider_view','provider:'+id);profileProvider=p;show('providerProfilePage');$('profileProviderName').textContent=p.name;$('profileProviderTitle').textContent=p.name;$('profileProviderCategory').textContent=p.category;$('profileProviderDesc').textContent=p.description;$('profilePrice').textContent=p.price;try{const st=await providerStats(id);const avg=st.ratings.length?st.ratings.reduce((a,x)=>a+Number(x.rating),0)/st.ratings.length:0;$('profileRating').textContent='⭐ '+Number(st.average||avg).toFixed(1);$('profileCompleted').textContent=st.completed;$('profileReviews').textContent=st.ratings.length;$('reviewsList')?.replaceChildren();$('profileReviewsList').innerHTML=st.ratings.length?st.ratings.map(r=>`<article class="review-card"><div>⭐ ${escapeHtml(r.rating)}/5</div><b>${escapeHtml(r.profiles?.full_name||'عميل')}</b><p>${escapeHtml(r.comment||'تقييم بدون تعليق')}</p><small>${formatDate(r.created_at)}</small></article>`).join(''):'<div class="empty-state"><div>⭐</div><h3>لا توجد تقييمات بعد</h3><p>كن أول عميل يقيّم هذه الخدمة.</p></div>'}catch(e){$('profileRating').textContent='⭐ 0.0';$('profileReviewsList').innerHTML='<div class="empty-state"><p>تعذر تحميل التقييمات.</p></div>'} }
async function openRatingForRequest(r){selectedRating=0;$('ratingComment').value='';$('ratingRequestTitle').textContent=(r.providerName||'مقدم الخدمة')+' — '+r.service;$('ratingMsg').textContent='';document.querySelectorAll('#ratingStars button').forEach(b=>b.classList.remove('selected'));$('ratingModal').classList.remove('hidden');$('ratingModal').setAttribute('aria-hidden','false');$('submitRating').dataset.requestId=r.id;$('submitRating').dataset.providerId=r.providerId||'';}
async function loadProviders(){
  if(!BACKEND_READY)return demoProviders();
  const {data,error}=await sb.from('providers').select('id,name,category,description,price,contact,user_id,commission_rate,created_at').eq('active',true).order('created_at',{ascending:false});
  if(error)throw error; return data||[];
}
function renderProviders(list){
  const box=$('providersList'); if(!box)return;
  const q=($('providerSearch')?.value||'').trim().toLowerCase(), cat=$('providerCategory')?.value||'';
  const filtered=list.filter(p=>(!cat||p.category===cat)&&(!q||[p.name,p.category,p.description,p.contact].some(v=>String(v||'').toLowerCase().includes(q))));
  box.innerHTML=filtered.length?filtered.map(p=>`<article class="provider-card"><div class="provider-avatar">🧑‍💼</div><span class="provider-category">${escapeHtml(p.category)}</span><h3>${escapeHtml(p.name)}</h3><p class="provider-desc">${escapeHtml(p.description)}</p><div class="provider-meta"><span>⭐ ${Number(p.avg_rating||0).toFixed(1)} (${Number(p.review_count||0)})</span><span class="provider-contact">${escapeHtml(p.contact||'')}</span></div><div class="provider-price">${escapeHtml(p.price)} جنيه <small>يبدأ من</small></div><div class="provider-actions"><button class="secondary profile-btn" data-profile="${escapeHtml(p.id)}">الملف والتقييمات</button><button class="primary" data-provider="${escapeHtml(p.id)}">اطلب الآن</button></div></article>`).join(''):'<div class="empty-state"><div>🔎</div><h3>لا توجد نتائج</h3><p>جرّب كلمة بحث أو تصنيفاً مختلفاً.</p></div>';
  box.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>chooseProvider(b.dataset.provider));box.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>showProviderProfile(b.dataset.profile));
}
async function showProviders(){show('providersPage');try{renderProviders(await loadProviders())}catch(e){$('providersList').innerHTML='<div class="empty-state"><h3>تعذر تحميل مقدمي الخدمات</h3><p>تأكد من إعداد قاعدة البيانات.</p></div>'}}
async function chooseProvider(id){if(!user())return show('loginPage');try{const list=await loadProviders();const p=list.find(x=>String(x.id)===String(id));if(!p)return toast('مقدم الخدمة غير موجود');selectedProvider=p;selectedService=p.category;const d=serviceInfo[p.category]||['🧑‍💼',p.category,'أرسل تفاصيل طلبك لمقدم الخدمة.'];$('modalIcon').textContent='🧑‍💼';$('modalTitle').textContent='طلب من '+p.name;$('modalDesc').textContent='الخدمة: '+p.category+' — تبدأ من '+p.price+' جنيه';$('requestNote').value='';setMsg('requestMsg','');$('serviceModal').classList.remove('hidden');$('serviceModal').setAttribute('aria-hidden','false');$('requestNote').focus()}catch(e){toast('تعذر فتح مقدم الخدمة')}}
function openService(title){if(title==='الطلبات')return showRequests();const d=serviceInfo[title]||['📋',title,'الخدمة متاحة للتجربة.'];selectedService=title;$('modalIcon').textContent=d[0];$('modalTitle').textContent=d[1];$('modalDesc').textContent=d[2];$('requestNote').value='';setMsg('requestMsg','');$('serviceModal').classList.remove('hidden');$('serviceModal').setAttribute('aria-hidden','false');$('requestNote').focus()}
function closeService(){selectedProvider=null;$('serviceModal').classList.add('hidden');$('serviceModal').setAttribute('aria-hidden','true')}
document.querySelectorAll('.service').forEach(b=>b.onclick=()=>openService(b.dataset.title));$('closeModal').onclick=closeService;$('serviceModal').addEventListener('click',e=>{if(e.target.id==='serviceModal')closeService()});
$('submitRequest').onclick=async()=>{const note=$('requestNote').value.trim();if(!note)return setMsg('requestMsg','اكتب تفاصيل الطلب أولاً.');try{const r=await createRequest(selectedService,note,selectedProvider?.id||null);if(selectedProvider){closeService();openCheckout({...r,providerName:selectedProvider.name,providerPrice:Number(selectedProvider.price),platformFee:Number(r.platformFee||Number(selectedProvider.price)*0.1)});return}setMsg('requestMsg','تم تسجيل الطلب بنجاح ✅',true);toast(BACKEND_READY?'تم حفظ الطلب في قاعدة البيانات':'تم حفظ الطلب في الوضع التجريبي');setTimeout(async()=>{closeService();await showHome()},650)}catch(e){setMsg('requestMsg','تعذر حفظ الطلب حالياً.')}};
$('serviceSearch').oninput=e=>{const q=e.target.value.trim();document.querySelectorAll('.service').forEach(b=>b.classList.toggle('hidden',q&&!b.innerText.includes(q)))};$('allServicesBtn').onclick=()=>{$('serviceSearch').value='';document.querySelectorAll('.service').forEach(b=>b.classList.remove('hidden'));toast('تم عرض جميع الخدمات')};$('clearNotices').onclick=markAllNotificationsRead;$('notifyBtn').onclick=openNotifications;$('closeNotifications').onclick=closeNotifications;$('markNotificationsRead').onclick=markAllNotificationsRead;$('notificationsModal').addEventListener('click',e=>{if(e.target.id==='notificationsModal')closeNotifications()});$('viewRequestsBtn').onclick=showRequests;$('backHomeBtn').onclick=showHome;

$('providerProfileBack').onclick=showProviders;$('profileShareBtn').onclick=async()=>{if(!profileProvider)return;const url=location.href.split('#')[0]+'#provider='+encodeURIComponent(profileProvider.id);try{if(navigator.share){await navigator.share({title:profileProvider.name,text:'شاهد مقدم الخدمة على خدماتي',url})}else{await navigator.clipboard.writeText(url);toast('تم نسخ رابط الملف 🔗')}}catch(e){if(e.name!=='AbortError')toast('تعذر مشاركة الرابط')}};$('profileRequestBtn').onclick=()=>profileProvider&&chooseProvider(profileProvider.id);document.querySelectorAll('#ratingStars button').forEach(b=>b.onclick=()=>{selectedRating=Number(b.dataset.rating);document.querySelectorAll('#ratingStars button').forEach(x=>x.classList.toggle('selected',Number(x.dataset.rating)<=selectedRating))});$('closeRatingModal').onclick=()=>{$('ratingModal').classList.add('hidden');$('ratingModal').setAttribute('aria-hidden','true')};$('ratingModal').addEventListener('click',e=>{if(e.target.id==='ratingModal')$('closeRatingModal').click()});$('submitRating').onclick=async()=>{if(!selectedRating)return setMsg('ratingMsg','اختر عدد النجوم أولاً.');const rid=$('submitRating').dataset.requestId,pid=$('submitRating').dataset.providerId,comment=$('ratingComment').value.trim();try{async function showPublic(){show('publicPage');try{const list=await loadProviders();const top=list.slice(0,3);$('publicProvidersList').innerHTML=top.length?top.map(p=>`<article class="provider-card"><div class="provider-avatar">🧑‍💼</div><span class="provider-category">${escapeHtml(p.category)}</span><h3>${escapeHtml(p.name)}</h3><p class="provider-desc">${escapeHtml(p.description)}</p><div class="provider-price">${escapeHtml(p.price)} جنيه <small>يبدأ من</small></div><div class="provider-actions"><button class="secondary public-profile" data-id="${escapeHtml(p.id)}">عرض الملف</button></div></article>`).join(''):'<div class="empty-state"><div>🧑‍💼</div><h3>لا يوجد مقدمو خدمات بعد</h3><p>كن أول من يضيف خدمته.</p></div>';document.querySelectorAll('.public-profile').forEach(b=>b.onclick=()=>showProviderProfile(b.dataset.id))}catch(e){$('publicProvidersList').innerHTML='<div class="empty-state"><h3>تعذر تحميل مقدمي الخدمات</h3></div>'}}
$('publicProvidersBtn')?.addEventListener('click',showProviders);$('publicSeeAll')?.addEventListener('click',showProviders);$('publicLoginBtn')?.addEventListener('click',()=>show('loginPage'));document.querySelectorAll('.service[data-service-slug]').forEach(b=>b.addEventListener('click',()=>openPublicService(b.dataset.serviceSlug)));

function handlePublicHash(){const sm=location.hash.match(/^#service=(.+)$/);if(sm){openPublicService(decodeURIComponent(sm[1]));return true}const m=location.hash.match(/^#provider=(.+)$/);if(m){showProviderProfile(decodeURIComponent(m[1]));return true}return false}
if(BACKEND_READY){const {error}=await sb.from('provider_reviews').insert({provider_id:Number(pid),request_id:Number(rid),user_id:sessionUser.id,rating:selectedRating,comment:comment||null});if(error)throw error}else{const a=JSON.parse(localStorage.getItem('khadamatiRatings')||'[]');a.push({providerId:pid,requestId:rid,rating:selectedRating,comment,created_at:new Date().toISOString(),profiles:{full_name:demoUser()?.name||'عميل'}});localStorage.setItem('khadamatiRatings',JSON.stringify(a));const u=demoUser();const rr=(u?.requestList||[]).find(x=>String(x.id)===String(rid));if(rr)rr.rated=true;saveDemoUser(u)}setMsg('ratingMsg','تم إرسال تقييمك ⭐',true);setTimeout(()=>{$('closeRatingModal').click();showRequests()},500)}catch(e){setMsg('ratingMsg','تعذر إرسال التقييم حالياً.')}};
$('providersBtn').onclick=showProviders;$('providersBackBtn').onclick=showHome;$('providerSearch').oninput=async()=>{try{renderProviders(await loadProviders())}catch{}};$('providerCategory').onchange=async()=>{try{renderProviders(await loadProviders())}catch{}};$('becomeProviderBtn').onclick=()=>{if(!user())return show('loginPage');$('providerName').value=user().name||'';$('providerContact').value=user().phone||'';setMsg('providerMsg','');$('providerModal').classList.remove('hidden');$('providerModal').setAttribute('aria-hidden','false')};$('closeProviderModal').onclick=()=>{$('providerModal').classList.add('hidden');$('providerModal').setAttribute('aria-hidden','true')};$('providerModal').addEventListener('click',e=>{if(e.target.id==='providerModal')$('closeProviderModal').click()});$('saveProviderBtn').onclick=async()=>{const n=$('providerName').value.trim(),c=$('providerService').value,d=$('providerDesc').value.trim(),pr=Number($('providerPrice').value),contact=$('providerContact').value.trim();if(n.length<2)return setMsg('providerMsg','اكتب اسم مقدم الخدمة.');if(d.length<5)return setMsg('providerMsg','اكتب وصفاً للخدمة.');if(!pr||pr<1)return setMsg('providerMsg','اكتب سعراً صحيحاً.');if(!validPhone(contact))return setMsg('providerMsg','اكتب رقم واتساب مصري صحيح.');try{async function showPublic(){show('publicPage');try{const list=await loadProviders();const top=list.slice(0,3);$('publicProvidersList').innerHTML=top.length?top.map(p=>`<article class="provider-card"><div class="provider-avatar">🧑‍💼</div><span class="provider-category">${escapeHtml(p.category)}</span><h3>${escapeHtml(p.name)}</h3><p class="provider-desc">${escapeHtml(p.description)}</p><div class="provider-price">${escapeHtml(p.price)} جنيه <small>يبدأ من</small></div><div class="provider-actions"><button class="secondary public-profile" data-id="${escapeHtml(p.id)}">عرض الملف</button></div></article>`).join(''):'<div class="empty-state"><div>🧑‍💼</div><h3>لا يوجد مقدمو خدمات بعد</h3><p>كن أول من يضيف خدمته.</p></div>';document.querySelectorAll('.public-profile').forEach(b=>b.onclick=()=>showProviderProfile(b.dataset.id))}catch(e){$('publicProvidersList').innerHTML='<div class="empty-state"><h3>تعذر تحميل مقدمي الخدمات</h3></div>'}}
$('publicProvidersBtn')?.addEventListener('click',showProviders);$('publicSeeAll')?.addEventListener('click',showProviders);$('publicLoginBtn')?.addEventListener('click',()=>show('loginPage'));document.querySelectorAll('.service[data-service-slug]').forEach(b=>b.addEventListener('click',()=>openPublicService(b.dataset.serviceSlug)));

function handlePublicHash(){const sm=location.hash.match(/^#service=(.+)$/);if(sm){openPublicService(decodeURIComponent(sm[1]));return true}const m=location.hash.match(/^#provider=(.+)$/);if(m){showProviderProfile(decodeURIComponent(m[1]));return true}return false}
if(BACKEND_READY){const {error}=await sb.from('providers').insert({user_id:sessionUser.id,name:n,category:c,description:d,price:pr,contact,active:true});if(error)throw error}else{const arr=demoProviders();arr.unshift({id:'demo-p'+Date.now(),name:n,category:c,description:d,price:pr,contact});saveProviders(arr)}setMsg('providerMsg','تم نشر خدمتك بنجاح ✅',true);setTimeout(()=>{ $('providerModal').classList.add('hidden');$('providerModal').setAttribute('aria-hidden','true');showProviders()},500)}catch(e){setMsg('providerMsg','تعذر نشر الخدمة حالياً.')}};
$('chatBackBtn').onclick=()=>{closeChat();showRequests()};$('sendChatBtn').onclick=sendChatMessage;$('chatInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendChatMessage()}});$('walletBtn').onclick=renderWallet;$('walletTopBtn').onclick=renderWallet;$('walletBackBtn').onclick=showHome;$('addBalanceBtn').onclick=addDemoBalance;$('closeCheckout').onclick=closeCheckout;$('checkoutModal').addEventListener('click',e=>{if(e.target.id==='checkoutModal')closeCheckout()});$('applyCouponBtn').onclick=applyCoupon;$('payNowBtn').onclick=payPending;
async function adminLogin(){if(!BACKEND_READY){showAdminDemo();return}try{const u=await loadProfile();if(!u||u.role!=='admin')return toast('هذا الحساب ليس حساب إدارة');showAdmin()}catch(e){toast('تعذر فتح لوحة الإدارة')}}
$('adminDemoBtn').onclick=adminLogin;$('adminBackBtn').onclick=showHome;
function showAdmin(){show('adminPage');renderAdmin()}
function showAdminDemo(){show('adminPage');renderAdmin()}
let adminCache={requests:[],users:[],providers:[],withdrawals:[],transactions:[]};
function adminMoney(n){return money(n)}
async function loadAdminData(){
  if(!BACKEND_READY){
    const u=demoUser()||{}; const requests=(u.requestList||[]).map(r=>({...r,userName:u.name,userPhone:u.phone}));
    const providers=demoProviders().map(p=>({...p,completed:requests.filter(r=>String(r.providerId)===String(p.id)&&r.status==='تم التنفيذ').length}));
    const transactions=JSON.parse(localStorage.getItem('khadamatiWalletTx')||'[]');
    return {requests,users:u.name?[{id:'demo',full_name:u.name,phone:u.phone,role:u.role||'user'}]:[],providers,withdrawals:JSON.parse(localStorage.getItem('khadamatiWithdrawals')||'[]'),transactions};
  }
  const [rq,us,pv,wd,tx]=await Promise.all([
    sb.from('service_requests').select('id,user_id,service,note,status,created_at,provider_id,provider_price,platform_fee,provider_net,payment_status,profiles(full_name,phone),providers(name)').order('created_at',{ascending:false}),
    sb.from('profiles').select('id,full_name,phone,role,created_at').order('created_at',{ascending:false}),
    sb.from('providers').select('id,user_id,name,category,description,price,active,commission_rate').order('created_at',{ascending:false}),
    sb.from('withdrawal_requests').select('id,user_id,amount,method,status,created_at,profiles(full_name,phone)').order('created_at',{ascending:false}),
    sb.from('wallet_transactions').select('id,user_id,type,amount,request_id,note,created_at,profiles(full_name,phone)').order('created_at',{ascending:false}).limit(100)
  ]);
  for(const x of [rq,us,pv,wd,tx])if(x.error)throw x.error;
  return {requests:(rq.data||[]).map(x=>({...x,userName:x.profiles?.full_name||'',userPhone:x.profiles?.phone||'',providerName:x.providers?.name||'',createdAt:x.created_at,providerPrice:x.provider_price,platformFee:x.platform_fee,paymentStatus:x.payment_status,providerNet:x.provider_net})),users:us.data||[],providers:pv.data||[],withdrawals:wd.data||[],transactions:tx.data||[]};
}
function adminFilter(arr,q,fields){if(!q)return arr;return arr.filter(x=>fields.some(k=>String(x[k]??'').toLowerCase().includes(q)))}
function renderAdminStats(d){
  const r=d.requests; const held=r.filter(x=>x.paymentStatus==='held').reduce((a,x)=>a+Number(x.providerPrice||0),0); const released=r.filter(x=>x.paymentStatus==='released').reduce((a,x)=>a+Number(x.providerPrice||0),0); const refunded=r.filter(x=>x.paymentStatus==='refunded').reduce((a,x)=>a+Number(x.providerPrice||0),0); const revenue=r.filter(x=>['held','released'].includes(x.paymentStatus)).reduce((a,x)=>a+Number(x.platformFee||0),0);
  $('adminTotalRequests').textContent=r.length; $('adminPending').textContent=r.filter(x=>x.status==='قيد المراجعة').length; $('adminUsers').textContent=d.users.length; $('adminRevenue').textContent=adminMoney(revenue); $('adminHeld').textContent=adminMoney(held); $('adminReleased').textContent=adminMoney(released); $('adminRefunded').textContent=adminMoney(refunded); $('adminWithdrawals').textContent=d.withdrawals.filter(x=>x.status==='قيد المراجعة').length;
}
function renderAdminOverview(d,q){
  const growth=d.growth; if(growth){const el=$('adminGrowthSummary');if(el)el.innerHTML=`<span>👀 زيارات مقدمين: ${growth.provider_views||0}</span><span>📄 زيارات خدمات: ${growth.service_views||0}</span><span>📝 طلبات من الأحداث: ${growth.requests_created||0}</span>`;}
  const recent=adminFilter(d.requests,q,['id','service','userName','status']).slice(0,6); $('adminRecentRequests').innerHTML=recent.length?recent.map(r=>`<div class="admin-list-row"><div><b>#${escapeHtml(r.id)}</b><small>${escapeHtml(r.service)} · ${escapeHtml(r.userName)}</small></div><span class="status ${statusClass(r.status)}">${escapeHtml(r.status)}</span></div>`).join(''):'<p class="muted">لا توجد بيانات.</p>';
  const top=[...d.providers].sort((a,b)=>Number(b.completed||0)-Number(a.completed||0)).slice(0,6); $('adminTopProviders').innerHTML=top.length?top.map(p=>`<div class="admin-list-row"><div><b>🧑‍💼 ${escapeHtml(p.name)}</b><small>${escapeHtml(p.category||'')} · يبدأ من ${adminMoney(p.price)}</small></div><strong>${Number(p.completed||0)} مكتملة</strong></div>`).join(''):'<p class="muted">لا توجد خدمات منشورة.</p>';
}
function renderAdminRequests(d,q){const f=adminFilter(d.requests,q,['id','service','userName','userPhone','status','note']);$('adminRequestsList').innerHTML=f.length?f.map(r=>`<article class="admin-request"><div class="admin-request-main"><div class="request-top"><span class="request-id">#${escapeHtml(r.id)}</span><span class="status ${statusClass(r.status)}">${escapeHtml(r.status)}</span></div><h3>${serviceInfo[r.service]?.[0]||'📋'} ${escapeHtml(r.service)}</h3><p>${escapeHtml(r.note)}</p><div class="admin-meta"><span>👤 ${escapeHtml(r.userName)}</span><span>📱 ${escapeHtml(r.userPhone)}</span><span>💰 ${r.providerPrice?adminMoney(r.providerPrice):'بدون دفع'}</span><span>🕒 ${formatDate(r.createdAt)}</span></div>${r.providerName?`<div class="admin-meta"><span>🧑‍💼 ${escapeHtml(r.providerName)}</span><span>🔐 ${escapeHtml(r.paymentStatus||'غير مطلوب')}</span></div>`:''}</div><div class="status-actions"><label>تغيير الحالة</label><select data-id="${escapeHtml(r.id)}" class="status-select"><option ${r.status==='قيد المراجعة'?'selected':''}>قيد المراجعة</option><option ${r.status==='جاري التنفيذ'?'selected':''}>جاري التنفيذ</option><option ${r.status==='تم التنفيذ'?'selected':''}>تم التنفيذ</option><option ${r.status==='ملغي'?'selected':''}>ملغي</option></select>${r.paymentStatus==='held'?`<button class="danger-btn refund-btn" data-id="${escapeHtml(r.id)}">↩️ استرداد المبلغ</button>`:''}</div></article>`).join(''):'<div class="empty-state"><div>📭</div><h3>لا توجد طلبات</h3><p>غيّر البحث أو انتظر طلبات جديدة.</p></div>';bindAdminActions()}
function renderAdminUsers(d,q){const f=adminFilter(d.users,q,['full_name','phone','role']);$('adminUsersList').innerHTML=f.length?f.map(u=>`<article class="admin-user"><div class="user-avatar">👤</div><div><b>${escapeHtml(u.full_name||'بدون اسم')}</b><small>${escapeHtml(u.phone||'')}</small></div><strong>${u.role==='admin'?'🛡️ إدارة':'مستخدم'}</strong></article>`).join(''):'<div class="empty-state"><div>👥</div><h3>لا يوجد مستخدمون</h3></div>'}
function renderAdminProviders(d,q){const f=adminFilter(d.providers,q,['name','category','description']);$('adminProvidersList').innerHTML=f.length?f.map(p=>`<article class="admin-user"><div class="user-avatar">🧑‍💼</div><div><b>${escapeHtml(p.name)}</b><small>${escapeHtml(p.category||'أخرى')} · ${adminMoney(p.price)} · عمولة ${Number(p.commission_rate||10)}%</small></div><strong>${p.active===false?'موقوف':'نشط'}</strong></article>`).join(''):'<div class="empty-state"><div>🧑‍💼</div><h3>لا يوجد مقدمو خدمات</h3></div>'}
function renderAdminFinance(d,q){
  const rows=[...d.withdrawals.map(x=>({...x,rowType:'withdrawal',createdAt:x.created_at||x.createdAt})),...d.transactions.map(x=>({...x,rowType:'transaction',createdAt:x.created_at||x.createdAt}))].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));
  const f=adminFilter(rows,q,['id','userName','method','status','type','note']);$('adminFinanceList').innerHTML=f.length?f.slice(0,80).map(x=>x.rowType==='withdrawal'?`<article class="finance-row"><div><b>🏦 طلب سحب #${escapeHtml(x.id)}</b><small>${escapeHtml(x.profiles?.full_name||x.userName||'')} · ${escapeHtml(x.method||'')}</small></div><strong>${adminMoney(x.amount)}</strong><select class="withdraw-status" data-id="${escapeHtml(x.id)}"><option ${x.status==='قيد المراجعة'?'selected':''}>قيد المراجعة</option><option ${x.status==='تم التحويل'?'selected':''}>تم التحويل</option><option ${x.status==='مرفوض'?'selected':''}>مرفوض</option></select></article>`:`<article class="finance-row"><div><b>${x.type==='earning'?'📈 أرباح':x.type==='payment'?'💳 دفع':x.type==='refund'?'↩️ استرداد':x.type==='fee'?'🏦 عمولة':'💰 عملية'}</b><small>${escapeHtml(x.profiles?.full_name||x.userName||'')} · ${escapeHtml(x.note||'')}</small></div><strong>${adminMoney(x.amount)}</strong></article>`).join(''):'<div class="empty-state"><div>💰</div><h3>لا توجد عمليات مالية</h3></div>';document.querySelectorAll('.withdraw-status').forEach(s=>s.onchange=()=>updateWithdrawal(s.dataset.id,s.value))}
function bindAdminActions(){document.querySelectorAll('.status-select').forEach(s=>s.onchange=()=>updateStatus(s.dataset.id,s.value));document.querySelectorAll('.refund-btn').forEach(b=>b.onclick=()=>refundRequest(b.dataset.id))}
async function renderAdmin(){try{adminCache=await loadAdminData();if(BACKEND_READY){const g=await sb.rpc('admin_growth_stats');adminCache.growth=(g.data||[])[0]||null}renderAdminStats(adminCache);const tab=document.querySelector('.admin-tab.active')?.dataset.tab||'overview';const q=($('adminSearch')?.value||'').trim().toLowerCase();['overview','requests','users','providers','finance'].forEach(t=>{const panel=$('admin'+t.charAt(0).toUpperCase()+t.slice(1)+'Panel');if(panel)panel.classList.toggle('hidden',t!==tab)});if(tab==='overview')renderAdminOverview(adminCache,q);if(tab==='requests')renderAdminRequests(adminCache,q);if(tab==='users')renderAdminUsers(adminCache,q);if(tab==='providers')renderAdminProviders(adminCache,q);if(tab==='finance')renderAdminFinance(adminCache,q)}catch(e){$('adminRecentRequests').innerHTML='<div class="empty-state"><h3>تعذر تحميل لوحة الإدارة</h3><p>تأكد من إعداد Supabase والصلاحيات ثم جرّب مرة أخرى.</p></div>'}}
async function updateStatus(id,status){try{async function showPublic(){show('publicPage');try{const list=await loadProviders();const top=list.slice(0,3);$('publicProvidersList').innerHTML=top.length?top.map(p=>`<article class="provider-card"><div class="provider-avatar">🧑‍💼</div><span class="provider-category">${escapeHtml(p.category)}</span><h3>${escapeHtml(p.name)}</h3><p class="provider-desc">${escapeHtml(p.description)}</p><div class="provider-price">${escapeHtml(p.price)} جنيه <small>يبدأ من</small></div><div class="provider-actions"><button class="secondary public-profile" data-id="${escapeHtml(p.id)}">عرض الملف</button></div></article>`).join(''):'<div class="empty-state"><div>🧑‍💼</div><h3>لا يوجد مقدمو خدمات بعد</h3><p>كن أول من يضيف خدمته.</p></div>';document.querySelectorAll('.public-profile').forEach(b=>b.onclick=()=>showProviderProfile(b.dataset.id))}catch(e){$('publicProvidersList').innerHTML='<div class="empty-state"><h3>تعذر تحميل مقدمي الخدمات</h3></div>'}}
$('publicProvidersBtn')?.addEventListener('click',showProviders);$('publicSeeAll')?.addEventListener('click',showProviders);$('publicLoginBtn')?.addEventListener('click',()=>show('loginPage'));document.querySelectorAll('.service[data-service-slug]').forEach(b=>b.addEventListener('click',()=>openPublicService(b.dataset.serviceSlug)));

function handlePublicHash(){const sm=location.hash.match(/^#service=(.+)$/);if(sm){openPublicService(decodeURIComponent(sm[1]));return true}const m=location.hash.match(/^#provider=(.+)$/);if(m){showProviderProfile(decodeURIComponent(m[1]));return true}return false}
if(BACKEND_READY){const {error}=await sb.from('service_requests').update({status}).eq('id',id);if(error)throw error}else{const u=demoUser();const r=(u?.requestList||[]).find(x=>String(x.id)===String(id));if(r){r.status=status;saveDemoUser(u)}}toast('تم تحديث الحالة إلى: '+status);renderAdmin()}catch(e){toast('تعذر تحديث الحالة')}}
async function refundRequest(id){try{async function showPublic(){show('publicPage');try{const list=await loadProviders();const top=list.slice(0,3);$('publicProvidersList').innerHTML=top.length?top.map(p=>`<article class="provider-card"><div class="provider-avatar">🧑‍💼</div><span class="provider-category">${escapeHtml(p.category)}</span><h3>${escapeHtml(p.name)}</h3><p class="provider-desc">${escapeHtml(p.description)}</p><div class="provider-price">${escapeHtml(p.price)} جنيه <small>يبدأ من</small></div><div class="provider-actions"><button class="secondary public-profile" data-id="${escapeHtml(p.id)}">عرض الملف</button></div></article>`).join(''):'<div class="empty-state"><div>🧑‍💼</div><h3>لا يوجد مقدمو خدمات بعد</h3><p>كن أول من يضيف خدمته.</p></div>';document.querySelectorAll('.public-profile').forEach(b=>b.onclick=()=>showProviderProfile(b.dataset.id))}catch(e){$('publicProvidersList').innerHTML='<div class="empty-state"><h3>تعذر تحميل مقدمي الخدمات</h3></div>'}}
$('publicProvidersBtn')?.addEventListener('click',showProviders);$('publicSeeAll')?.addEventListener('click',showProviders);$('publicLoginBtn')?.addEventListener('click',()=>show('loginPage'));document.querySelectorAll('.service[data-service-slug]').forEach(b=>b.addEventListener('click',()=>openPublicService(b.dataset.serviceSlug)));

function handlePublicHash(){const sm=location.hash.match(/^#service=(.+)$/);if(sm){openPublicService(decodeURIComponent(sm[1]));return true}const m=location.hash.match(/^#provider=(.+)$/);if(m){showProviderProfile(decodeURIComponent(m[1]));return true}return false}
if(BACKEND_READY){const {error}=await sb.rpc('refund_request_payment',{p_request_id:Number(id)});if(error)throw error}else{const u=demoUser();const r=(u?.requestList||[]).find(x=>String(x.id)===String(id));if(!r||r.paymentStatus!=='held')throw Error();u.walletBalance=Number(u.walletBalance||0)+Number(r.providerPrice||0);r.paymentStatus='refunded';saveDemoUser(u)}toast('تم استرداد المبلغ للعميل ↩️');renderAdmin()}catch(e){toast('تعذر استرداد المبلغ')}}
async function updateWithdrawal(id,status){try{async function showPublic(){show('publicPage');try{const list=await loadProviders();const top=list.slice(0,3);$('publicProvidersList').innerHTML=top.length?top.map(p=>`<article class="provider-card"><div class="provider-avatar">🧑‍💼</div><span class="provider-category">${escapeHtml(p.category)}</span><h3>${escapeHtml(p.name)}</h3><p class="provider-desc">${escapeHtml(p.description)}</p><div class="provider-price">${escapeHtml(p.price)} جنيه <small>يبدأ من</small></div><div class="provider-actions"><button class="secondary public-profile" data-id="${escapeHtml(p.id)}">عرض الملف</button></div></article>`).join(''):'<div class="empty-state"><div>🧑‍💼</div><h3>لا يوجد مقدمو خدمات بعد</h3><p>كن أول من يضيف خدمته.</p></div>';document.querySelectorAll('.public-profile').forEach(b=>b.onclick=()=>showProviderProfile(b.dataset.id))}catch(e){$('publicProvidersList').innerHTML='<div class="empty-state"><h3>تعذر تحميل مقدمي الخدمات</h3></div>'}}
$('publicProvidersBtn')?.addEventListener('click',showProviders);$('publicSeeAll')?.addEventListener('click',showProviders);$('publicLoginBtn')?.addEventListener('click',()=>show('loginPage'));document.querySelectorAll('.service[data-service-slug]').forEach(b=>b.addEventListener('click',()=>openPublicService(b.dataset.serviceSlug)));

function handlePublicHash(){const sm=location.hash.match(/^#service=(.+)$/);if(sm){openPublicService(decodeURIComponent(sm[1]));return true}const m=location.hash.match(/^#provider=(.+)$/);if(m){showProviderProfile(decodeURIComponent(m[1]));return true}return false}
if(BACKEND_READY){const {error}=await sb.from('withdrawal_requests').update({status}).eq('id',id);if(error)throw error}else{const a=JSON.parse(localStorage.getItem('khadamatiWithdrawals')||'[]');const x=a.find(v=>String(v.id)===String(id));if(x)x.status=status;localStorage.setItem('khadamatiWithdrawals',JSON.stringify(a))}toast('تم تحديث طلب السحب');renderAdmin()}catch(e){toast('تعذر تحديث طلب السحب')}}

// V3.5 — مساعد خدماتي الذكي (محرك ترشيح محلي آمن، بدون مفاتيح سرية داخل المتصفح)
const aiState={step:0,answers:{}};
const aiQuestions=[
 {key:'goal',title:'إيه اللي محتاج تعمله؟',options:[['website','عمل موقع أو صفحة هبوط'],['marketing','تسويق أو إعلانات'],['design','تصميم صور أو هوية'],['code','برمجة أو تعديل برنامج'],['maintenance','صيانة أو إصلاح'],['other','خدمة أخرى']]},
 {key:'budget',title:'ميزانيتك التقريبية؟',options:[['low','حتى 200 جنيه'],['mid','من 200 إلى 500 جنيه'],['high','أكثر من 500 جنيه'],['unknown','مش عارف لسه']]},
 {key:'speed',title:'إمتى محتاج الخدمة؟',options:[['urgent','بسرعة'],['normal','خلال أيام'],['flex','مش مستعجل']]},
];
function openAiAssistant(){if(!user())return show('loginPage');aiState.step=0;aiState.answers={};$('aiResult').classList.add('hidden');$('aiNextBtn').textContent='التالي';$('aiBackBtn').classList.add('hidden');$('aiModal').classList.remove('hidden');$('aiModal').setAttribute('aria-hidden','false');renderAiStep()}
function closeAiAssistant(){$('aiModal').classList.add('hidden');$('aiModal').setAttribute('aria-hidden','true')}
function renderAiStep(){const q=aiQuestions[aiState.step];$('aiStepHint').textContent=`السؤال ${aiState.step+1} من ${aiQuestions.length}`;$('aiWizard').innerHTML=`<div class="ai-question"><h3>${escapeHtml(q.title)}</h3>${q.options.map(([v,l])=>`<label class="ai-option ${aiState.answers[q.key]===v?'selected':''}"><input type="radio" name="ai-${q.key}" value="${v}" ${aiState.answers[q.key]===v?'checked':''}> <span>${escapeHtml(l)}</span></label>`).join('')}</div>`;document.querySelectorAll('.ai-option').forEach(o=>o.onclick=()=>{document.querySelectorAll('.ai-option').forEach(x=>x.classList.remove('selected'));o.classList.add('selected');o.querySelector('input').checked=true});$('aiBackBtn').classList.toggle('hidden',aiState.step===0)}
function aiCategory(goal){return goal==='marketing'?'تسويق':goal==='design'?'تصميم':goal==='code'||goal==='website'?'برمجة':goal==='maintenance'?'صيانة':'أخرى'}
function aiScoreProvider(p,a){let score=0;const cat=aiCategory(a.goal);if(p.category===cat)score+=60;if(a.budget==='low'&&Number(p.price)<=200)score+=25;if(a.budget==='mid'&&Number(p.price)<=500)score+=20;if(a.budget==='high')score+=15;if(a.budget==='unknown')score+=10;if(a.speed==='urgent')score+=5;score+=Math.min(10,Number(p.rating||0)*2);return score}
function aiRecommend(){const a=aiState.answers,cat=aiCategory(a.goal),providers=demoProviders().map(p=>({...p,score:aiScoreProvider(p,a)})).sort((x,y)=>y.score-x.score);const top=providers.filter(p=>p.category===cat).slice(0,3);const picks=(top.length?top:providers).slice(0,3);$('aiStepHint').textContent='الترشيح جاهز';$('aiWizard').innerHTML='';$('aiNextBtn').textContent='ابدأ طلبًا جديدًا';$('aiResult').classList.remove('hidden');$('aiResult').innerHTML=`<h3>🎯 أنسب تصنيف لك: ${escapeHtml(cat)}</h3><p class="muted">بناءً على هدفك وميزانيتك والسرعة، هذه أفضل الترشيحات المتاحة الآن.</p><div class="ai-recommendations">${picks.map(p=>`<div class="ai-provider"><div><b>${escapeHtml(p.name)}</b><small>${escapeHtml(p.category)} · يبدأ من ${Number(p.price||0)} جنيه${p.rating?' · ⭐ '+Number(p.rating).toFixed(1):''}</small></div><button class="secondary ai-pick" data-id="${escapeHtml(p.id)}">عرض المقدم</button></div>`).join('')}</div><p class="muted" style="margin-bottom:0">ملاحظة: هذا الترشيح آلي داخل الموقع، ويمكن لاحقًا ربطه بخدمة ذكاء اصطناعي حقيقية من خادم آمن.</p>`;document.querySelectorAll('.ai-pick').forEach(b=>b.onclick=()=>{closeAiAssistant();openProviderProfile(b.dataset.id)})}
function aiNext(){if(aiState.step<aiQuestions.length){const q=aiQuestions[aiState.step],sel=document.querySelector(`input[name="ai-${q.key}"]:checked`);if(!sel)return toast('اختار إجابة الأول 👌');aiState.answers[q.key]=sel.value;if(aiState.step===aiQuestions.length-1){aiState.step=aiQuestions.length;aiRecommend()}else{aiState.step++;renderAiStep()}}else{closeAiAssistant();show('providersPage');renderProviders()} }
function aiBack(){if(aiState.step>0&&aiState.step<aiQuestions.length){aiState.step--;renderAiStep()}}
$('aiAssistantBtn')?.addEventListener('click',openAiAssistant);$('closeAiModal')?.addEventListener('click',closeAiAssistant);$('aiNextBtn')?.addEventListener('click',aiNext);$('aiBackBtn')?.addEventListener('click',aiBack);
document.querySelectorAll('.service[data-service-slug]').forEach(b=>b.addEventListener('click',()=>openPublicService(b.dataset.serviceSlug)));
document.querySelectorAll('.admin-tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.admin-tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');renderAdmin()});$('adminSearch').oninput=renderAdmin;

async function showPublic(){show('publicPage');try{const list=await loadProviders();const top=list.slice(0,3);$('publicProvidersList').innerHTML=top.length?top.map(p=>`<article class="provider-card"><div class="provider-avatar">🧑‍💼</div><span class="provider-category">${escapeHtml(p.category)}</span><h3>${escapeHtml(p.name)}</h3><p class="provider-desc">${escapeHtml(p.description)}</p><div class="provider-price">${escapeHtml(p.price)} جنيه <small>يبدأ من</small></div><div class="provider-actions"><button class="secondary public-profile" data-id="${escapeHtml(p.id)}">عرض الملف</button></div></article>`).join(''):'<div class="empty-state"><div>🧑‍💼</div><h3>لا يوجد مقدمو خدمات بعد</h3><p>كن أول من يضيف خدمته.</p></div>';document.querySelectorAll('.public-profile').forEach(b=>b.onclick=()=>showProviderProfile(b.dataset.id))}catch(e){$('publicProvidersList').innerHTML='<div class="empty-state"><h3>تعذر تحميل مقدمي الخدمات</h3></div>'}}
$('publicProvidersBtn')?.addEventListener('click',showProviders);$('publicSeeAll')?.addEventListener('click',showProviders);$('publicLoginBtn')?.addEventListener('click',()=>show('loginPage'));document.querySelectorAll('.service[data-service-slug]').forEach(b=>b.addEventListener('click',()=>openPublicService(b.dataset.serviceSlug)));

function handlePublicHash(){const sm=location.hash.match(/^#service=(.+)$/);if(sm){openPublicService(decodeURIComponent(sm[1]));return true}const m=location.hash.match(/^#provider=(.+)$/);if(m){showProviderProfile(decodeURIComponent(m[1]));return true}return false}
if(BACKEND_READY){$('backendStatus').textContent='الوضع الحقيقي جاهز للاتصال بقاعدة البيانات.';$('backendStatus').classList.add('success-msg');sb.auth.getSession().then(async({data})=>{if(data.session){try{await loadProfile();notificationChannel&&sb.removeChannel(notificationChannel);notificationChannel=subscribeNotifications();showHome()}catch{show('loginPage')}}else if(!handlePublicHash())showPublic()});sb.auth.onAuthStateChange(async()=>{try{await loadProfile();notificationChannel&&sb.removeChannel(notificationChannel);notificationChannel=subscribeNotifications();if(sessionUser)renderNotifications()}catch{}})}else{seedDemoNotifications();if(currentDemo())showHome();else if(!handlePublicHash())showPublic()}

window.addEventListener('hashchange',handlePublicHash);
