-- خدماتي V2.1 — مخطط Supabase الآمن
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  phone text unique not null,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.service_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  service text not null,
  note text not null,
  status text not null default 'قيد المراجعة' check (status in ('قيد المراجعة','جاري التنفيذ','تم التنفيذ','ملغي')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.service_requests enable row level security;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;

-- مهم: المستخدم يستطيع إنشاء ملفه، لكنه لا يستطيع تعديل الدور أو رقم الهاتف.
drop policy if exists "profiles own read" on public.profiles;
drop policy if exists "profiles own insert" on public.profiles;
drop policy if exists "profiles own update" on public.profiles;
drop policy if exists "profiles admin read" on public.profiles;
create policy "profiles own read" on public.profiles for select using (id = auth.uid() or public.is_admin());
create policy "profiles own insert" on public.profiles for insert with check (id = auth.uid() and role = 'user');
create policy "profiles own update name only" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid() and role = 'user' and phone = (select p.phone from public.profiles p where p.id = auth.uid()));

-- الطلبات: المستخدم يرى ويضيف طلباته فقط، والإدارة ترى وتغير الحالة.
drop policy if exists "requests own read" on public.service_requests;
drop policy if exists "requests own insert" on public.service_requests;
drop policy if exists "admin update requests" on public.service_requests;
create policy "requests own read" on public.service_requests for select using (user_id = auth.uid() or public.is_admin());
create policy "requests own insert" on public.service_requests for insert with check (user_id = auth.uid());
create policy "admin update requests" on public.service_requests for update using (public.is_admin()) with check (public.is_admin());

-- بعد إنشاء حسابك، نفّذ هذا الأمر مرة واحدة لتحويله إلى مدير:
-- update public.profiles set role='admin' where phone='01xxxxxxxxx';

-- V2.2: سوق مقدمي الخدمات
create table if not exists public.providers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  category text not null,
  description text not null,
  price numeric(12,2) not null check (price >= 0),
  contact text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.providers enable row level security;

alter table public.service_requests add column if not exists provider_id bigint references public.providers(id) on delete set null;

 drop policy if exists "providers public read active" on public.providers;
 drop policy if exists "providers own insert" on public.providers;
 drop policy if exists "providers own update" on public.providers;
create policy "providers public read active" on public.providers for select using (active = true or user_id = auth.uid() or public.is_admin());
create policy "providers own insert" on public.providers for insert with check (user_id = auth.uid());
create policy "providers own update" on public.providers for update using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());

 drop policy if exists "requests own read" on public.service_requests;
create policy "requests own read" on public.service_requests for select using (user_id = auth.uid() or public.is_admin());

-- V2.3: ملفات مقدمي الخدمات + التقييمات + تتبع العمولة
alter table public.providers add column if not exists commission_rate numeric(5,2) not null default 10 check (commission_rate >= 0 and commission_rate <= 100);
alter table public.service_requests add column if not exists provider_price numeric(12,2);
alter table public.service_requests add column if not exists platform_fee numeric(12,2) not null default 0;

create table if not exists public.provider_reviews (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references public.providers(id) on delete cascade,
  request_id bigint not null unique references public.service_requests(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now()
);
alter table public.provider_reviews enable row level security;
drop policy if exists "reviews public read" on public.provider_reviews;
drop policy if exists "reviews own insert" on public.provider_reviews;
create policy "reviews public read" on public.provider_reviews for select using (true);
create policy "reviews own insert" on public.provider_reviews for insert with check (
  user_id = auth.uid() and exists (
    select 1 from public.service_requests r
    where r.id = request_id and r.user_id = auth.uid() and r.provider_id = provider_id and r.status = 'تم التنفيذ'
  )
);

create or replace function public.get_provider_stats(p_provider_id bigint)
returns table(completed bigint, reviews bigint, average numeric)
language sql stable security definer set search_path = public
as $$
  select
    (select count(*) from public.service_requests r where r.provider_id = p_provider_id and r.status='تم التنفيذ'),
    (select count(*) from public.provider_reviews v where v.provider_id = p_provider_id),
    coalesce((select round(avg(v.rating)::numeric,1) from public.provider_reviews v where v.provider_id = p_provider_id),0);
$$;

grant execute on function public.get_provider_stats(bigint) to anon, authenticated;

-- V3.0/V3.1: المحفظة + الوساطة المالية (Escrow)
alter table public.service_requests add column if not exists payment_status text not null default 'not_required';
alter table public.service_requests drop constraint if exists service_requests_payment_status_check;
alter table public.service_requests add constraint service_requests_payment_status_check check (payment_status in ('not_required','pending','held','paid','released','refunded'));
alter table public.service_requests add column if not exists provider_net numeric(12,2) not null default 0;
alter table public.service_requests add column if not exists platform_fee numeric(12,2) not null default 0;

create table if not exists public.wallet_accounts (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  balance numeric(12,2) not null default 0 check (balance >= 0),
  updated_at timestamptz not null default now()
);
create table if not exists public.wallet_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('deposit','payment','earning','withdrawal','refund','fee')),
  amount numeric(12,2) not null,
  request_id bigint references public.service_requests(id) on delete set null,
  note text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.withdrawal_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(12,2) not null check (amount > 0),
  method text not null default 'واتساب للتواصل',
  status text not null default 'قيد المراجعة' check (status in ('قيد المراجعة','تم التحويل','مرفوض')),
  created_at timestamptz not null default now()
);
alter table public.wallet_accounts enable row level security;
alter table public.wallet_transactions enable row level security;
alter table public.withdrawal_requests enable row level security;
drop policy if exists "wallet own read" on public.wallet_accounts;
drop policy if exists "wallet own insert" on public.wallet_accounts;
create policy "wallet own read" on public.wallet_accounts for select using (user_id = auth.uid() or public.is_admin());
create policy "wallet own insert" on public.wallet_accounts for insert with check (user_id = auth.uid());
drop policy if exists "wallet tx own read" on public.wallet_transactions;
create policy "wallet tx own read" on public.wallet_transactions for select using (user_id = auth.uid() or public.is_admin());
drop policy if exists "withdraw own read" on public.withdrawal_requests;
drop policy if exists "withdraw own insert" on public.withdrawal_requests;
create policy "withdraw own read" on public.withdrawal_requests for select using (user_id = auth.uid() or public.is_admin());
create policy "withdraw own insert" on public.withdrawal_requests for insert with check (user_id = auth.uid());

-- العميل يدفع: المال يُحجز في Escrow ولا يصل لمقدم الخدمة بعد.
create or replace function public.pay_for_request(p_request_id bigint)
returns boolean language plpgsql security definer set search_path = public
as $$
declare r public.service_requests; bal numeric; total numeric;
begin
  select * into r from public.service_requests where id=p_request_id and user_id=auth.uid() for update;
  if not found then raise exception 'الطلب غير موجود'; end if;
  if r.provider_id is null then raise exception 'هذا الطلب لا يحتاج دفعاً'; end if;
  if r.payment_status in ('held','released') then return true; end if;
  if r.payment_status='refunded' then raise exception 'لا يمكن دفع طلب مسترد'; end if;
  total := coalesce(r.provider_price,0);
  if total <= 0 then raise exception 'سعر الطلب غير صحيح'; end if;
  insert into public.wallet_accounts(user_id,balance) values(auth.uid(),0) on conflict(user_id) do nothing;
  select balance into bal from public.wallet_accounts where user_id=auth.uid() for update;
  if bal < total then raise exception 'الرصيد غير كافٍ'; end if;
  update public.wallet_accounts set balance=balance-total,updated_at=now() where user_id=auth.uid();
  insert into public.wallet_transactions(user_id,type,amount,request_id,note) values(auth.uid(),'payment',-total,p_request_id,'حجز قيمة الطلب في الوساطة #'||p_request_id);
  update public.service_requests set payment_status='held' where id=p_request_id;
  return true;
end; $$;
grant execute on function public.pay_for_request(bigint) to authenticated;

-- العميل يؤكد الاستلام: تحرير المبلغ لمقدم الخدمة واحتساب العمولة مرة واحدة.
create or replace function public.release_request_payment(p_request_id bigint)
returns boolean language plpgsql security definer set search_path = public
as $$
declare r public.service_requests; fee numeric; net numeric;
begin
  select * into r from public.service_requests where id=p_request_id and user_id=auth.uid() for update;
  if not found then raise exception 'الطلب غير موجود'; end if;
  if r.status <> 'تم التنفيذ' then raise exception 'لا يمكن تحرير المبلغ قبل اكتمال الطلب'; end if;
  if r.payment_status='released' then return true; end if;
  if r.payment_status <> 'held' then raise exception 'لا يوجد مبلغ محجوز لهذا الطلب'; end if;
  fee := coalesce(r.platform_fee,0); net := greatest(coalesce(r.provider_price,0)-fee,0);
  update public.service_requests set payment_status='released', provider_net=net where id=p_request_id;
  update public.wallet_accounts wa set balance=wa.balance+net,updated_at=now()
    from public.providers p where p.id=r.provider_id and wa.user_id=p.user_id;
  insert into public.wallet_transactions(user_id,type,amount,request_id,note)
    select p.user_id,'earning',net,p_request_id,'أرباح بعد تأكيد استلام الطلب #'||p_request_id
    from public.providers p where p.id=r.provider_id;
  insert into public.wallet_transactions(user_id,type,amount,request_id,note)
    select p.user_id,'fee',-fee,p_request_id,'عمولة خدماتي للطلب #'||p_request_id
    from public.providers p where p.id=r.provider_id and fee > 0;
  return true;
end; $$;
grant execute on function public.release_request_payment(bigint) to authenticated;

-- الإدارة تستطيع رد المبلغ المحجوز في الحالات المناسبة.
create or replace function public.refund_request_payment(p_request_id bigint)
returns boolean language plpgsql security definer set search_path = public
as $$
declare r public.service_requests; total numeric;
begin
  if not public.is_admin() then raise exception 'غير مصرح'; end if;
  select * into r from public.service_requests where id=p_request_id for update;
  if not found then raise exception 'الطلب غير موجود'; end if;
  if r.payment_status='refunded' then return true; end if;
  if r.payment_status <> 'held' then raise exception 'لا يوجد مبلغ محجوز قابل للاسترداد'; end if;
  total:=coalesce(r.provider_price,0);
  insert into public.wallet_accounts(user_id,balance) values(r.user_id,0) on conflict(user_id) do nothing;
  update public.wallet_accounts set balance=balance+total,updated_at=now() where user_id=r.user_id;
  insert into public.wallet_transactions(user_id,type,amount,request_id,note) values(r.user_id,'refund',total,p_request_id,'استرداد مبلغ الطلب #'||p_request_id);
  update public.service_requests set payment_status='refunded' where id=p_request_id;
  return true;
end; $$;
grant execute on function public.refund_request_payment(bigint) to authenticated;

-- للشحن الحقيقي: لا تُضاف أموال حقيقية من الواجهة. يتم ربط بوابة دفع ثم استدعاء خادم آمن.

-- V3.2: لوحة إدارة متقدمة
DROP POLICY IF EXISTS "withdraw admin update" ON public.withdrawal_requests;
CREATE POLICY "withdraw admin update" ON public.withdrawal_requests
FOR UPDATE USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "withdraw admin read" ON public.withdrawal_requests;
CREATE POLICY "withdraw admin read" ON public.withdrawal_requests
FOR SELECT USING (user_id = auth.uid() OR public.is_admin());

-- السماح للإدارة بقراءة العمليات المالية فقط؛ المستخدم يقرأ عملياته هو.
DROP POLICY IF EXISTS "wallet tx own read" ON public.wallet_transactions;
CREATE POLICY "wallet tx own read" ON public.wallet_transactions
FOR SELECT USING (user_id = auth.uid() OR public.is_admin());

-- الإدارة فقط تستطيع تحديث حالة طلب السحب. التحويل المالي الحقيقي يجب تنفيذه عبر خادم آمن/بوابة دفع.

-- V3.3: الإشعارات الفورية
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  body text not null,
  type text not null default 'system' check (type in ('request','status','payment','earning','refund','system')),
  read boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.notifications enable row level security;
drop policy if exists "notifications own read" on public.notifications;
drop policy if exists "notifications own update" on public.notifications;
create policy "notifications own read" on public.notifications for select using (user_id = auth.uid());
create policy "notifications own update" on public.notifications for update using (user_id = auth.uid()) with check (user_id = auth.uid());

grant select, update on public.notifications to authenticated;
grant usage, select on sequence public.notifications_id_seq to authenticated;

create or replace function public.notify_request_events()
returns trigger language plpgsql security definer set search_path = public
as $$
declare provider_user uuid;
begin
  if TG_OP = 'INSERT' then
    if NEW.provider_id is not null then
      select user_id into provider_user from public.providers where id = NEW.provider_id;
      if provider_user is not null then
        insert into public.notifications(user_id,title,body,type)
        values(provider_user,'طلب خدمة جديد','وصل طلب جديد لك برقم #'||NEW.id||' — راجع الطلب وابدأ التنفيذ.','request');
      end if;
    end if;
  elsif TG_OP = 'UPDATE' then
    if NEW.status is distinct from OLD.status then
      insert into public.notifications(user_id,title,body,type)
      values(NEW.user_id,'تحديث حالة الطلب','تم تغيير حالة طلبك #'||NEW.id||' إلى «'||NEW.status||'».','status');
    end if;
    if NEW.payment_status is distinct from OLD.payment_status and NEW.payment_status in ('released','refunded') then
      if NEW.payment_status='released' then
        select user_id into provider_user from public.providers where id=NEW.provider_id;
        if provider_user is not null then
          insert into public.notifications(user_id,title,body,type)
          values(provider_user,'تم تحرير أرباحك','تم تأكيد استلام الطلب #'||NEW.id||' وتم تحرير مستحقاتك.','earning');
        end if;
      elsif NEW.payment_status='refunded' then
        insert into public.notifications(user_id,title,body,type)
        values(NEW.user_id,'تم استرداد المبلغ','تم استرداد مبلغ الطلب #'||NEW.id||' إلى محفظتك.','refund');
      end if;
    end if;
  end if;
  return NEW;
end; $$;

drop trigger if exists trg_notify_request_events on public.service_requests;
create trigger trg_notify_request_events
after insert or update of status,payment_status on public.service_requests
for each row execute function public.notify_request_events();

-- تفعيل Realtime على جدول الإشعارات من لوحة Supabase إذا لم يكن مفعلاً تلقائياً.
-- لا يتم إنشاء إشعارات من الواجهة مباشرة في الوضع الحقيقي؛ قاعدة البيانات هي مصدر الإشعار.


-- V3.4: محادثات مرتبطة بالطلبات
create table if not exists public.service_messages (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.service_requests(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  receiver_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 1000),
  created_at timestamptz not null default now()
);
alter table public.service_messages enable row level security;
drop policy if exists "messages participants read" on public.service_messages;
drop policy if exists "messages participants insert" on public.service_messages;
create policy "messages participants read" on public.service_messages for select using (sender_id = auth.uid() or receiver_id = auth.uid());
create policy "messages participants insert" on public.service_messages for insert with check (
  sender_id = auth.uid() and exists (
    select 1 from public.service_requests r
    left join public.providers p on p.id=r.provider_id
    where r.id=request_id and (r.user_id=auth.uid() or p.user_id=auth.uid()) and receiver_id <> auth.uid()
  )
);
grant select, insert on public.service_messages to authenticated;
grant usage, select on sequence public.service_messages_id_seq to authenticated;

create or replace function public.notify_new_message()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.notifications(user_id,title,body,type)
  values(NEW.receiver_id,'رسالة جديدة','لديك رسالة جديدة في طلب #'||NEW.request_id||'.','system');
  return NEW;
end; $$;
drop trigger if exists trg_notify_new_message on public.service_messages;
create trigger trg_notify_new_message after insert on public.service_messages for each row execute function public.notify_new_message();


-- V4.1: أكواد خصم حقيقية من قاعدة البيانات + تحليلات أحداث المنصة
create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text unique not null,
  type text not null check (type in ('percent','fixed')),
  value numeric(12,2) not null check (value > 0),
  min_amount numeric(12,2) not null default 0 check (min_amount >= 0),
  max_discount numeric(12,2),
  usage_limit integer,
  used_count integer not null default 0 check (used_count >= 0),
  active boolean not null default true,
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  created_at timestamptz not null default now()
);
alter table public.coupons enable row level security;
drop policy if exists "coupons public read active" on public.coupons;
create policy "coupons public read active" on public.coupons for select using (active=true and (starts_at is null or starts_at<=now()) and (expires_at is null or expires_at>now()));
drop policy if exists "coupons admin all" on public.coupons;
create policy "coupons admin all" on public.coupons for all using (public.is_admin()) with check (public.is_admin());
grant select on public.coupons to anon, authenticated;

insert into public.coupons(code,type,value,min_amount,max_discount,usage_limit) values
('KHADAMATI10','percent',10,100,100,null),
('WELCOME50','fixed',50,300,50,null)
on conflict(code) do nothing;

create or replace function public.validate_coupon(p_code text,p_amount numeric)
returns table(code text,type text,value numeric,min_amount numeric,max_discount numeric,discount numeric)
language plpgsql security definer set search_path=public
as $$
declare c public.coupons; d numeric;
begin
  select * into c from public.coupons where upper(code)=upper(trim(p_code)) and active=true and (starts_at is null or starts_at<=now()) and (expires_at is null or expires_at>now()) and (usage_limit is null or used_count<usage_limit) limit 1;
  if not found or p_amount < c.min_amount then return; end if;
  if c.type='percent' then d:=p_amount*c.value/100; else d:=c.value; end if;
  if c.max_discount is not null then d:=least(d,c.max_discount); end if;
  d:=least(greatest(d,0),p_amount);
  return query select c.code,c.type,c.value,c.min_amount,c.max_discount,d;
end; $$;
grant execute on function public.validate_coupon(text,numeric) to anon, authenticated;

create table if not exists public.platform_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  event_type text not null,
  page text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.platform_events enable row level security;
drop policy if exists "events own insert" on public.platform_events;
create policy "events own insert" on public.platform_events for insert with check (user_id=auth.uid());
drop policy if exists "events admin read" on public.platform_events;
create policy "events admin read" on public.platform_events for select using (public.is_admin());
grant insert on public.platform_events to authenticated;
grant select on public.platform_events to authenticated;
grant usage,select on sequence public.platform_events_id_seq to authenticated;

create or replace function public.admin_growth_stats()
returns table(total_events bigint, visitors bigint, provider_views bigint, service_views bigint, requests_created bigint)
language sql stable security definer set search_path=public
as $$
select count(*), count(distinct user_id), count(*) filter(where event_type='provider_view'), count(*) filter(where event_type='service_view'), count(*) filter(where event_type='request_created') from public.platform_events;
$$;
grant execute on function public.admin_growth_stats() to authenticated;


-- V4.2: برنامج الإحالة
create table if not exists public.referral_codes (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  code text unique not null,
  created_at timestamptz not null default now()
);
alter table public.referral_codes enable row level security;
drop policy if exists "referral own read" on public.referral_codes;
create policy "referral own read" on public.referral_codes for select using (user_id=auth.uid());
drop policy if exists "referral own insert" on public.referral_codes;
create policy "referral own insert" on public.referral_codes for insert with check (user_id=auth.uid());
grant select,insert on public.referral_codes to authenticated;

create table if not exists public.referral_events (
  id bigint generated by default as identity primary key,
  referrer_id uuid not null references public.profiles(id) on delete cascade,
  referred_id uuid references public.profiles(id) on delete set null,
  code text not null,
  status text not null default 'registered' check(status in ('registered','qualified','rewarded')),
  reward numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);
alter table public.referral_events enable row level security;
drop policy if exists "referral events own read" on public.referral_events;
create policy "referral events own read" on public.referral_events for select using (referrer_id=auth.uid() or referred_id=auth.uid());
grant select on public.referral_events to authenticated;

create or replace function public.my_referral_stats()
returns table(invites bigint, qualified bigint, rewards numeric) language sql stable security definer set search_path=public as $$
select count(*), count(*) filter(where status in ('qualified','rewarded')), coalesce(sum(reward) filter(where status='rewarded'),0)
from public.referral_events where referrer_id=auth.uid();
$$;
grant execute on function public.my_referral_stats() to authenticated;

-- إنشاء كود الإحالة عند الطلب من التطبيق.
create or replace function public.ensure_referral_code()
returns text language plpgsql security definer set search_path=public as $$
declare c text;
begin
  select code into c from public.referral_codes where user_id=auth.uid();
  if c is null then c:='KH-'||upper(substr(replace(auth.uid()::text,'-',''),1,8)); insert into public.referral_codes(user_id,code) values(auth.uid(),c) on conflict(user_id) do nothing; end if;
  return c;
end; $$;
grant execute on function public.ensure_referral_code() to authenticated;

-- خدماتي V5.0 — الباقات ومصادر الدخل
create table if not exists public.subscription_plans (
  id text primary key,
  name text not null,
  monthly_price numeric(12,2) not null check (monthly_price >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.provider_subscriptions (
  id bigint generated by default as identity primary key,
  provider_id uuid not null references public.profiles(id) on delete cascade,
  plan_id text not null references public.subscription_plans(id),
  status text not null default 'active' check (status in ('active','cancelled','expired')),
  started_at timestamptz not null default now(),
  ends_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.subscription_plans enable row level security;
alter table public.provider_subscriptions enable row level security;

drop policy if exists "plans public read" on public.subscription_plans;
create policy "plans public read" on public.subscription_plans for select using (active = true);

drop policy if exists "subscriptions own read" on public.provider_subscriptions;
create policy "subscriptions own read" on public.provider_subscriptions for select using (provider_id = auth.uid() or public.is_admin());

drop policy if exists "subscriptions own insert" on public.provider_subscriptions;
create policy "subscriptions own insert" on public.provider_subscriptions for insert with check (provider_id = auth.uid());

drop policy if exists "subscriptions own update" on public.provider_subscriptions;
create policy "subscriptions own update" on public.provider_subscriptions for update using (provider_id = auth.uid() or public.is_admin()) with check (provider_id = auth.uid() or public.is_admin());

insert into public.subscription_plans (id,name,monthly_price) values
('starter','البداية',49),('pro','المحترف',99),('business','الأعمال',199)
on conflict (id) do update set name=excluded.name, monthly_price=excluded.monthly_price;

-- V5.1: الدفع الحقيقي الآمن — جلسة دفع + Webhook
create table if not exists public.payment_orders (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.service_requests(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(12,2) not null check (amount >= 0),
  currency text not null default 'EGP',
  coupon_code text,
  status text not null default 'created' check (status in ('created','pending','paid','failed','refunded')),
  external_id text unique,
  checkout_url text,
  created_at timestamptz not null default now(),
  paid_at timestamptz
);
alter table public.payment_orders enable row level security;
drop policy if exists "payment orders own read" on public.payment_orders;
create policy "payment orders own read" on public.payment_orders for select using (user_id = auth.uid() or public.is_admin());

create or replace function public.create_payment_order(p_request_id bigint, p_coupon_code text default null)
returns bigint language plpgsql security definer set search_path = public
as $$
declare r public.service_requests; total numeric; discount numeric := 0; oid bigint;
begin
  select * into r from public.service_requests where id=p_request_id and user_id=auth.uid() for update;
  if not found then raise exception 'الطلب غير موجود'; end if;
  if r.provider_id is null then raise exception 'الطلب غير مرتبط بمقدم خدمة'; end if;
  if r.payment_status in ('held','released') then raise exception 'الطلب مدفوع بالفعل'; end if;
  total := coalesce(r.provider_price,0) + coalesce(r.platform_fee,0);
  if total <= 0 then raise exception 'قيمة الدفع غير صحيحة'; end if;
  if p_coupon_code is not null and length(trim(p_coupon_code)) > 0 then
    select coalesce(discount,0) into discount from public.validate_coupon(upper(trim(p_coupon_code)), coalesce(r.provider_price,0)) limit 1;
  end if;
  total := greatest(0,total-discount);
  insert into public.payment_orders(request_id,user_id,amount,coupon_code,status) values(p_request_id,auth.uid(),total,nullif(upper(trim(p_coupon_code)),''),'created') returning id into oid;
  return oid;
end; $$;
grant execute on function public.create_payment_order(bigint,text) to authenticated;

create or replace function public.confirm_payment_webhook(p_external_id text, p_status text, p_amount numeric)
returns boolean language plpgsql security definer set search_path = public
as $$
declare o public.payment_orders;
begin
  select * into o from public.payment_orders where external_id=p_external_id for update;
  if not found then raise exception 'payment order not found'; end if;
  if o.status='paid' then return true; end if;
  if abs(o.amount-p_amount) > 0.01 then raise exception 'amount mismatch'; end if;
  if lower(p_status)='paid' then
    update public.payment_orders set status='paid',paid_at=now() where id=o.id;
    update public.service_requests set payment_status='held' where id=o.request_id and user_id=o.user_id and payment_status='pending';
    insert into public.wallet_transactions(user_id,type,amount,request_id,note) values(o.user_id,'payment',-o.amount,o.request_id,'دفع مؤكد عبر بوابة الدفع');
  elsif lower(p_status) in ('failed','refunded') then
    update public.payment_orders set status=lower(p_status) where id=o.id;
  end if;
  return true;
end; $$;
-- هذه الدالة تستدعى من Edge Function باستخدام service_role، ولا تمنح للمستخدمين.
revoke all on function public.confirm_payment_webhook(text,text,numeric) from public, anon, authenticated;


-- V5.3: اشتراكات Push للأجهزة
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  endpoint text not null unique,
  subscription jsonb not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;
drop policy if exists "push own read" on public.push_subscriptions;
drop policy if exists "push own insert" on public.push_subscriptions;
drop policy if exists "push own update" on public.push_subscriptions;
drop policy if exists "push own delete" on public.push_subscriptions;
create policy "push own read" on public.push_subscriptions for select using (user_id = auth.uid() or public.is_admin());
create policy "push own insert" on public.push_subscriptions for insert with check (user_id = auth.uid());
create policy "push own update" on public.push_subscriptions for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "push own delete" on public.push_subscriptions for delete using (user_id = auth.uid());
grant select,insert,update,delete on public.push_subscriptions to authenticated;
grant usage,select on sequence public.push_subscriptions_id_seq to authenticated;

-- V5.4: الثقة والتحقق من مقدمي الخدمات
alter table public.providers add column if not exists verified boolean not null default false;
alter table public.providers add column if not exists verification_status text not null default 'none' check (verification_status in ('none','pending','approved','rejected'));

create table if not exists public.provider_verification_requests (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references public.providers(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  document_type text not null check (document_type in ('id','business','portfolio')),
  document_path text not null,
  note text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);
alter table public.provider_verification_requests enable row level security;
drop policy if exists "verification own read" on public.provider_verification_requests;
drop policy if exists "verification own insert" on public.provider_verification_requests;
drop policy if exists "verification admin read" on public.provider_verification_requests;
create policy "verification own read" on public.provider_verification_requests for select using (user_id=auth.uid() or public.is_admin());
create policy "verification own insert" on public.provider_verification_requests for insert with check (user_id=auth.uid() and exists(select 1 from public.providers p where p.id=provider_id and p.user_id=auth.uid()));
grant select,insert on public.provider_verification_requests to authenticated;

insert into storage.buckets (id,name,public) values ('verification-docs','verification-docs',false) on conflict (id) do nothing;
drop policy if exists "verification storage own upload" on storage.objects;
drop policy if exists "verification storage own read" on storage.objects;
drop policy if exists "verification storage admin read" on storage.objects;
create policy "verification storage own upload" on storage.objects for insert to authenticated with check (bucket_id='verification-docs' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "verification storage own read" on storage.objects for select to authenticated using (bucket_id='verification-docs' and ((storage.foldername(name))[1]=auth.uid()::text or public.is_admin()));

create or replace function public.admin_review_verification(p_request_id bigint, p_status text)
returns boolean language plpgsql security definer set search_path=public
as $$
declare r public.provider_verification_requests;
begin
  if not public.is_admin() then raise exception 'admin only'; end if;
  if p_status not in ('approved','rejected','pending') then raise exception 'invalid status'; end if;
  select * into r from public.provider_verification_requests where id=p_request_id for update;
  if not found then raise exception 'verification request not found'; end if;
  update public.provider_verification_requests set status=p_status, reviewed_at=case when p_status='pending' then null else now() end where id=p_request_id;
  update public.providers set verified=(p_status='approved'), verification_status=p_status where id=r.provider_id;
  return true;
end; $$;
revoke all on function public.admin_review_verification(bigint,text) from public, anon, authenticated;

-- V5.5: مكافحة الاحتيال والبلاغات والنزاعات
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  provider_id bigint references public.providers(id) on delete set null,
  request_id bigint references public.service_requests(id) on delete set null,
  reason text not null check (reason in ('fraud','abuse','no_delivery','payment','other')),
  details text not null,
  status text not null default 'open' check (status in ('open','investigating','resolved','dismissed')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);
create table if not exists public.disputes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  request_id bigint references public.service_requests(id) on delete set null,
  provider_id bigint references public.providers(id) on delete set null,
  reason text not null check (reason in ('fraud','abuse','no_delivery','payment','other')),
  details text not null,
  status text not null default 'open' check (status in ('open','investigating','resolved','dismissed')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

alter table public.reports enable row level security;
alter table public.disputes enable row level security;
drop policy if exists "reports own read" on public.reports;
drop policy if exists "reports own insert" on public.reports;
drop policy if exists "reports admin read" on public.reports;
create policy "reports own read" on public.reports for select using (reporter_id=auth.uid() or public.is_admin());
create policy "reports own insert" on public.reports for insert with check (reporter_id=auth.uid());
drop policy if exists "disputes own read" on public.disputes;
drop policy if exists "disputes own insert" on public.disputes;
create policy "disputes own read" on public.disputes for select using (user_id=auth.uid() or public.is_admin());
create policy "disputes own insert" on public.disputes for insert with check (user_id=auth.uid());
revoke all on public.reports, public.disputes from anon;
grant select,insert on public.reports, public.disputes to authenticated;

-- تحديث الحالة لا يتم من العميل مباشرة؛ الأفضل لاحقًا استخدام دالة security definer للإدارة.


-- V5.6: نظام الثقة الذكي
create table if not exists public.provider_risk_events (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references public.providers(id) on delete cascade,
  admin_id uuid references auth.users(id) on delete set null,
  points integer not null check (points between -25 and 25),
  reason text,
  created_at timestamptz not null default now()
);
alter table public.provider_risk_events enable row level security;
drop policy if exists "risk admin read" on public.provider_risk_events;
create policy "risk admin read" on public.provider_risk_events for select using (public.is_admin());
revoke all on public.provider_risk_events from anon, authenticated;
grant select on public.provider_risk_events to authenticated;

create or replace function public.provider_trust_score(p_provider_id bigint)
returns table(score integer, level text, risk_penalty integer)
language sql stable security definer set search_path=public
as $$
with p as (select * from public.providers where id=p_provider_id),
r as (select coalesce(avg(rating),0) avg_rating,count(*) review_count from public.provider_ratings where provider_id=p_provider_id),
c as (select count(*) filter(where status='تم التنفيذ') completed from public.service_requests where provider_id=p_provider_id),
risk as (select greatest(0,least(25,coalesce(sum(points),0))) penalty from public.provider_risk_events where provider_id=p_provider_id)
select greatest(0,least(100,round(35+r.avg_rating*9+least(5,r.review_count)*2+least(5,c.completed)*2+case when p.verified then 10 else 0 end-risk.penalty)::int)),
case when round(35+r.avg_rating*9+least(5,r.review_count)*2+least(5,c.completed)*2+case when p.verified then 10 else 0 end-risk.penalty)>=85 then 'ممتاز' when round(35+r.avg_rating*9+least(5,r.review_count)*2+least(5,c.completed)*2+case when p.verified then 10 else 0 end-risk.penalty)>=70 then 'موثوق' when round(35+r.avg_rating*9+least(5,r.review_count)*2+least(5,c.completed)*2+case when p.verified then 10 else 0 end-risk.penalty)>=50 then 'جيد' else 'يحتاج مراجعة' end,
risk.penalty from p,r,c,risk;
$$;
revoke all on function public.provider_trust_score(bigint) from public, anon; grant execute on function public.provider_trust_score(bigint) to authenticated;

create or replace function public.admin_provider_trust()
returns table(provider_id bigint,name text,score integer,level text,risk_penalty integer)
language sql stable security definer set search_path=public
as $$ select p.id,p.name,t.score,t.level,t.risk_penalty from public.providers p cross join lateral public.provider_trust_score(p.id) t where public.is_admin() order by t.score desc; $$;
revoke all on function public.admin_provider_trust() from public, anon, authenticated; grant execute on function public.admin_provider_trust() to authenticated;

create or replace function public.admin_adjust_trust_risk(p_provider_id bigint,p_delta integer)
returns boolean language plpgsql security definer set search_path=public
as $$ begin if not public.is_admin() then raise exception 'admin only'; end if; if p_delta not between -25 and 25 then raise exception 'invalid delta'; end if; insert into public.provider_risk_events(provider_id,admin_id,points,reason) values(p_provider_id,auth.uid(),p_delta,'تعديل إداري لدرجة المخاطر'); return true; end; $$;
revoke all on function public.admin_adjust_trust_risk(bigint,integer) from public, anon, authenticated; grant execute on function public.admin_adjust_trust_risk(bigint,integer) to authenticated;

-- V6.0: محرك المخاطر الذكي (Rule-based Risk Engine)
-- لا يعتمد على نموذج ذكاء اصطناعي خارجي؛ القواعد قابلة للمراجعة ويمكن تطويرها لاحقًا.
create or replace function public.admin_risk_alerts()
returns table(
  provider_id bigint,
  name text,
  active boolean,
  verified boolean,
  score integer,
  avg_rating numeric,
  review_count bigint,
  open_reports bigint,
  open_disputes bigint
)
language sql stable security definer set search_path=public
as $$
with ratings as (
  select provider_id, avg(rating)::numeric as avg_rating, count(*)::bigint as review_count
  from public.provider_ratings group by provider_id
), reports as (
  select provider_id, count(*)::bigint as open_reports from public.reports
  where provider_id is not null and status in ('open','investigating') group by provider_id
), disputes as (
  select provider_id, count(*)::bigint as open_disputes from public.disputes
  where provider_id is not null and status in ('open','investigating') group by provider_id
), trust as (
  select p.id, (public.provider_trust_score(p.id)).score as score from public.providers p
)
select p.id,p.name,p.active,p.verified,coalesce(t.score,0),coalesce(r.avg_rating,0),coalesce(r.review_count,0),coalesce(x.open_reports,0),coalesce(d.open_disputes,0)
from public.providers p
left join ratings r on r.provider_id=p.id
left join reports x on x.provider_id=p.id
left join disputes d on d.provider_id=p.id
left join trust t on t.id=p.id
where public.is_admin()
order by (coalesce(x.open_reports,0)*20 + coalesce(d.open_disputes,0)*18 + case when coalesce(t.score,0)<50 then 15 else 0 end) desc;
$$;
revoke all on function public.admin_risk_alerts() from public, anon, authenticated;
grant execute on function public.admin_risk_alerts() to authenticated;


-- V6.3 — سوق العروض والمنافسة
create table if not exists public.market_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  service text not null,
  title text not null,
  details text not null,
  budget numeric(12,2),
  deadline_days integer,
  status text not null default 'open' check (status in ('open','awarded','cancelled','closed')),
  selected_offer_id bigint,
  created_at timestamptz not null default now()
);
create table if not exists public.service_offers (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.market_requests(id) on delete cascade,
  provider_id bigint not null references public.providers(id) on delete cascade,
  price numeric(12,2) not null check (price > 0),
  delivery_days integer,
  message text,
  status text not null default 'pending' check (status in ('pending','accepted','rejected','withdrawn')),
  created_at timestamptz not null default now(),
  unique(request_id, provider_id)
);
alter table public.market_requests enable row level security;
alter table public.service_offers enable row level security;
drop policy if exists "market requests own read" on public.market_requests;
drop policy if exists "market requests own insert" on public.market_requests;
drop policy if exists "market requests admin read" on public.market_requests;
drop policy if exists "offers participants read" on public.service_offers;
drop policy if exists "providers insert offers" on public.service_offers;
create policy "market requests own read" on public.market_requests for select using (user_id=auth.uid() or public.is_admin());
create policy "market requests own insert" on public.market_requests for insert with check (user_id=auth.uid());
create policy "market requests admin read" on public.market_requests for select using (public.is_admin());
create policy "offers participants read" on public.service_offers for select using (exists(select 1 from public.market_requests r where r.id=request_id and (r.user_id=auth.uid() or public.is_admin())) or exists(select 1 from public.providers p where p.id=provider_id and p.user_id=auth.uid()));
create policy "providers insert offers" on public.service_offers for insert with check (exists(select 1 from public.providers p where p.id=provider_id and p.user_id=auth.uid()));
-- V6.4: تحويل العرض المقبول إلى طلب خدمة فعلي وربطه بدورة الدفع/الوساطة
alter table public.service_requests add column if not exists source_market_request_id bigint references public.market_requests(id) on delete set null;
alter table public.service_requests add column if not exists agreed_deadline_days integer;
alter table public.service_requests add column if not exists accepted_at timestamptz;

create or replace function public.accept_service_offer(p_request_id bigint,p_offer_id bigint)
returns bigint language plpgsql security definer set search_path=public as $$
declare req public.market_requests; off public.service_offers; prov public.providers; new_id bigint; fee numeric; net numeric;
begin
 select * into req from public.market_requests where id=p_request_id and user_id=auth.uid() and status='open' for update;
 if not found then raise exception 'not_allowed'; end if;
 select * into off from public.service_offers where id=p_offer_id and request_id=p_request_id and status='pending' for update;
 if not found then raise exception 'offer_not_found'; end if;
 select * into prov from public.providers where id=off.provider_id and active=true;
 if not found then raise exception 'provider_unavailable'; end if;
 fee := round(off.price * coalesce(prov.commission_rate,10) / 100, 2);
 net := greatest(off.price-fee,0);
 insert into public.service_requests(user_id,service,note,status,provider_id,provider_price,platform_fee,provider_net,payment_status,source_market_request_id,agreed_deadline_days,accepted_at)
 values(req.user_id,req.service,req.title||E'\n\n'||req.details,'قيد المراجعة',off.provider_id,off.price,fee,net,'pending',req.id,off.delivery_days,now())
 returning id into new_id;
 update public.service_offers set status=case when id=p_offer_id then 'accepted' else 'rejected' end where request_id=p_request_id;
 update public.market_requests set status='awarded',selected_offer_id=p_offer_id where id=p_request_id;
 insert into public.notifications(user_id,title,body,type) values(req.user_id,'تم اختيار عرضك','تم تحويل العرض المختار إلى طلب خدمة #'||new_id||' ويمكنك الآن متابعة الدفع والتنفيذ.','request');
 insert into public.notifications(user_id,title,body,type)
 select p.user_id,'تم اختيار عرضك','العميل اختارك لتنفيذ طلب #'||new_id||' بسعر '||off.price||' جنيه.','request' from public.providers p where p.id=off.provider_id;
 return new_id;
end; $$;
revoke all on function public.accept_service_offer(bigint,bigint) from public,anon;
grant execute on function public.accept_service_offer(bigint,bigint) to authenticated;


-- V7.5: تنفيذ حقيقي وحفظ التسليمات في Supabase
create table if not exists public.execution_states (
  request_id bigint primary key references public.service_requests(id) on delete cascade,
  phase text not null default 'requirements' check (phase in ('requirements','in_progress','delivered','revision','approved')),
  progress integer not null default 15 check (progress between 0 and 100),
  revision_count integer not null default 0,
  last_revision text,
  approved_at timestamptz,
  updated_at timestamptz not null default now()
);
create table if not exists public.execution_events (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.service_requests(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  label text not null,
  actor_label text not null default 'النظام',
  created_at timestamptz not null default now()
);
create table if not exists public.execution_deliveries (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.service_requests(id) on delete cascade,
  uploader_id uuid not null references auth.users(id) on delete cascade,
  file_path text not null unique,
  file_name text not null,
  mime_type text,
  file_size bigint,
  note text,
  version integer not null default 1,
  created_at timestamptz not null default now()
);
alter table public.execution_states enable row level security;
alter table public.execution_events enable row level security;
alter table public.execution_deliveries enable row level security;
drop policy if exists "execution states participants" on public.execution_states;
drop policy if exists "execution events participants" on public.execution_events;
drop policy if exists "execution deliveries participants" on public.execution_deliveries;
drop policy if exists "execution events insert participants" on public.execution_events;
drop policy if exists "execution deliveries insert participants" on public.execution_deliveries;
create policy "execution states participants" on public.execution_states for all using (
  exists(select 1 from public.service_requests r where r.id=request_id and (r.user_id=auth.uid() or exists(select 1 from public.providers p where p.id=r.provider_id and p.user_id=auth.uid()) or public.is_admin()))
) with check (
  exists(select 1 from public.service_requests r where r.id=request_id and (r.user_id=auth.uid() or exists(select 1 from public.providers p where p.id=r.provider_id and p.user_id=auth.uid()) or public.is_admin()))
);
create policy "execution events participants" on public.execution_events for select using (
  exists(select 1 from public.service_requests r where r.id=request_id and (r.user_id=auth.uid() or exists(select 1 from public.providers p where p.id=r.provider_id and p.user_id=auth.uid()) or public.is_admin()))
);
create policy "execution events insert participants" on public.execution_events for insert with check (
  exists(select 1 from public.service_requests r where r.id=request_id and (r.user_id=auth.uid() or exists(select 1 from public.providers p where p.id=r.provider_id and p.user_id=auth.uid()) or public.is_admin()))
);
create policy "execution deliveries participants" on public.execution_deliveries for select using (
  exists(select 1 from public.service_requests r where r.id=request_id and (r.user_id=auth.uid() or exists(select 1 from public.providers p where p.id=r.provider_id and p.user_id=auth.uid()) or public.is_admin()))
);
create policy "execution deliveries insert participants" on public.execution_deliveries for insert with check (
  uploader_id=auth.uid() and exists(select 1 from public.service_requests r where r.id=request_id and (r.user_id=auth.uid() or exists(select 1 from public.providers p where p.id=r.provider_id and p.user_id=auth.uid()) or public.is_admin()))
);

-- Private bucket for actual delivery files
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('execution-deliveries','execution-deliveries',false,104857600,array['image/*','video/*','application/pdf','application/zip','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'])
on conflict (id) do update set file_size_limit=104857600, public=false;
drop policy if exists "execution storage read participants" on storage.objects;
drop policy if exists "execution storage insert participants" on storage.objects;
create policy "execution storage read participants" on storage.objects for select using (
  bucket_id='execution-deliveries' and exists(select 1 from public.service_requests r where r.id::text=split_part(name,'/',1) and (r.user_id=auth.uid() or exists(select 1 from public.providers p where p.id=r.provider_id and p.user_id=auth.uid()) or public.is_admin()))
);
create policy "execution storage insert participants" on storage.objects for insert with check (
  bucket_id='execution-deliveries' and auth.uid() is not null and exists(select 1 from public.service_requests r where r.id::text=split_part(name,'/',1) and (r.user_id=auth.uid() or exists(select 1 from public.providers p where p.id=r.provider_id and p.user_id=auth.uid()) or public.is_admin()))
);

-- V7.6: مركز النزاعات المحمي + أدلة + قرارات الإدارة عبر RPC
create table if not exists public.dispute_evidence (
  id bigint generated by default as identity primary key,
  dispute_id bigint not null references public.disputes(id) on delete cascade,
  uploader_id uuid not null references auth.users(id) on delete cascade,
  file_path text not null unique,
  file_name text not null,
  mime_type text,
  file_size bigint,
  note text,
  created_at timestamptz not null default now()
);
alter table public.dispute_evidence enable row level security;
drop policy if exists "dispute evidence participants read" on public.dispute_evidence;
drop policy if exists "dispute evidence owner insert" on public.dispute_evidence;
create policy "dispute evidence participants read" on public.dispute_evidence for select using (
  uploader_id=auth.uid() or public.is_admin() or exists(select 1 from public.disputes d where d.id=dispute_id and d.user_id=auth.uid())
);
create policy "dispute evidence owner insert" on public.dispute_evidence for insert with check (
  uploader_id=auth.uid() and exists(select 1 from public.disputes d where d.id=dispute_id and d.user_id=auth.uid())
);
revoke all on public.dispute_evidence from anon;
grant select,insert on public.dispute_evidence to authenticated;

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('dispute-evidence','dispute-evidence',false,52428800,array['image/*','video/*','application/pdf','application/zip','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'])
on conflict (id) do update set public=false,file_size_limit=52428800;
drop policy if exists "dispute evidence storage read" on storage.objects;
drop policy if exists "dispute evidence storage insert" on storage.objects;
create policy "dispute evidence storage read" on storage.objects for select using (
  bucket_id='dispute-evidence' and (
    public.is_admin() or exists(select 1 from public.dispute_evidence e join public.disputes d on d.id=e.dispute_id where e.file_path=name and (d.user_id=auth.uid() or e.uploader_id=auth.uid()))
  )
);
create policy "dispute evidence storage insert" on storage.objects for insert with check (
  bucket_id='dispute-evidence' and auth.uid() is not null and exists(
    select 1 from public.disputes d where d.id::text=split_part(name,'/',1) and d.user_id=auth.uid()
  )
);

create or replace function public.admin_resolve_dispute(p_dispute_id bigint,p_action text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare d public.disputes; r public.service_requests;
begin
  if not public.is_admin() then raise exception 'غير مصرح'; end if;
  if p_action not in ('investigate','release','refund','dismiss') then raise exception 'قرار غير صالح'; end if;
  select * into d from public.disputes where id=p_dispute_id for update;
  if not found then raise exception 'النزاع غير موجود'; end if;
  if d.request_id is not null then select * into r from public.service_requests where id=d.request_id for update; end if;
  if p_action='release' then
    if r.id is null then raise exception 'النزاع غير مرتبط بطلب'; end if;
    if r.payment_status <> 'held' then raise exception 'لا يوجد مبلغ محجوز قابل للتحرير'; end if;
    if r.status <> 'تم التنفيذ' then raise exception 'لا يمكن تحرير المبلغ قبل اكتمال الطلب'; end if;
    perform public.release_request_payment(r.id);
    update public.disputes set status='resolved',reviewed_at=now() where id=d.id;
  elsif p_action='refund' then
    if r.id is null then raise exception 'النزاع غير مرتبط بطلب'; end if;
    if r.payment_status <> 'held' then raise exception 'لا يوجد مبلغ محجوز قابل للاسترداد'; end if;
    perform public.refund_request_payment(r.id);
    update public.disputes set status='resolved',reviewed_at=now() where id=d.id;
  elsif p_action='investigate' then
    update public.disputes set status='investigating',reviewed_at=null where id=d.id;
  else
    update public.disputes set status='dismissed',reviewed_at=now() where id=d.id;
  end if;
  insert into public.notifications(user_id,title,body,type) values(d.user_id,'تحديث النزاع','تم تحديث حالة النزاع #'||d.id||'.','system');
  if d.provider_id is not null then insert into public.notifications(user_id,title,body,type) select p.user_id,'تحديث نزاع على طلب','تم تحديث حالة النزاع #'||d.id||'.','system' from public.providers p where p.id=d.provider_id; end if;
  return jsonb_build_object('ok',true,'message','تم تنفيذ القرار بنجاح');
end; $$;
revoke all on function public.admin_resolve_dispute(bigint,text) from public,anon,authenticated;
grant execute on function public.admin_resolve_dispute(bigint,text) to authenticated;

-- V7.7: سمعة وتقييمات موثقة (اختياري عند استخدام Supabase)
create table if not exists public.provider_reputation_events (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references public.providers(id) on delete cascade,
  request_id bigint references public.service_requests(id) on delete set null,
  event_type text not null check (event_type in ('completed','rating','dispute','verification','response')),
  weight numeric not null default 0,
  note text,
  created_at timestamptz not null default now()
);
alter table public.provider_reputation_events enable row level security;
drop policy if exists "reputation events admin read" on public.provider_reputation_events;
create policy "reputation events admin read" on public.provider_reputation_events for select using (public.is_admin());
revoke all on public.provider_reputation_events from anon;
grant select on public.provider_reputation_events to authenticated;

create or replace function public.provider_reputation_summary(p_provider_id bigint)
returns table(score numeric, level text, average_rating numeric, review_count bigint, completed_count bigint, verified boolean)
language sql security definer set search_path=public as $$
with base as (
  select p.id,p.verified,coalesce((select count(*) from service_requests r where r.provider_id=p.id and r.status='تم التنفيذ'),0) completed_count,
  coalesce((select avg(pr.rating) from provider_reviews pr where pr.provider_id=p.id),0) average_rating,
  coalesce((select count(*) from provider_reviews pr where pr.provider_id=p.id),0) review_count
  from providers p where p.id=p_provider_id
), calc as (
  select *, greatest(0,least(100,round(25+average_rating*12+least(review_count,10)*2+least(completed_count,10)*1.5+case when verified then 10 else 0 end))) score
  from base
)
select score, case when score>=90 then 'ممتاز' when score>=78 then 'موثوق' when score>=62 then 'جيد' else 'يحتاج تحسين' end, round(average_rating,2),review_count,completed_count,verified from calc;
$$;
revoke all on function public.provider_reputation_summary(bigint) from public,anon;
grant execute on function public.provider_reputation_summary(bigint) to authenticated;

-- V8.0 SECURITY HARDENING: لا تكشف أكواد الخصم وقيَمها للزوار مباشرة.
-- التحقق من الكوبون يتم عبر الدالة الآمنة validate_coupon للمستخدم المسجل فقط.
drop policy if exists "coupons public read active" on public.coupons;
revoke select on public.coupons from anon, authenticated;
revoke execute on function public.validate_coupon(text,numeric) from anon;
grant execute on function public.validate_coupon(text,numeric) to authenticated;


-- V9.0: مركز النزاعات والبلاغات — تحديث الحالة عبر دوال إدارية فقط
create or replace function public.admin_update_report_status(p_id bigint,p_status text)
returns boolean language plpgsql security definer set search_path=public
as $$ begin
  if not public.is_admin() then raise exception 'admin only'; end if;
  if p_status not in ('open','investigating','resolved','dismissed') then raise exception 'invalid status'; end if;
  update public.reports set status=p_status, reviewed_at=case when p_status in ('resolved','dismissed') then now() else reviewed_at end where id=p_id;
  if not found then raise exception 'report not found'; end if;
  return true;
end; $$;
revoke all on function public.admin_update_report_status(bigint,text) from public, anon, authenticated;
grant execute on function public.admin_update_report_status(bigint,text) to authenticated;

create or replace function public.admin_update_dispute_status(p_id bigint,p_status text)
returns boolean language plpgsql security definer set search_path=public
as $$ begin
  if not public.is_admin() then raise exception 'admin only'; end if;
  if p_status not in ('open','investigating','resolved','dismissed') then raise exception 'invalid status'; end if;
  update public.disputes set status=p_status, reviewed_at=case when p_status in ('resolved','dismissed') then now() else reviewed_at end where id=p_id;
  if not found then raise exception 'dispute not found'; end if;
  return true;
end; $$;
revoke all on function public.admin_update_dispute_status(bigint,text) from public, anon, authenticated;
grant execute on function public.admin_update_dispute_status(bigint,text) to authenticated;


-- V10.0: مركز تشغيل الإدارة + سجل التدقيق (Audit Log)
create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.admin_audit_log enable row level security;
drop policy if exists "audit admin read" on public.admin_audit_log;
create policy "audit admin read" on public.admin_audit_log for select using (public.is_admin());
revoke all on public.admin_audit_log from anon, authenticated;
grant select on public.admin_audit_log to authenticated;


create or replace function public.write_admin_audit(
  p_action text, p_entity_type text, p_entity_id text default null, p_metadata jsonb default '{}'::jsonb
) returns bigint language plpgsql security definer set search_path=public as $$
declare v_id bigint;
begin
  insert into public.admin_audit_log(actor_id,action,entity_type,entity_id,metadata)
  values(auth.uid(),left(p_action,120),left(p_entity_type,80),left(p_entity_id,120),coalesce(p_metadata,'{}'::jsonb)) returning id into v_id;
  return v_id;
end; $$;
revoke all on function public.write_admin_audit(text,text,text,jsonb) from public, anon, authenticated;

create or replace function public.admin_ops_summary()
returns table(
  open_reports bigint, open_disputes bigint, pending_withdrawals bigint,
  held_payments numeric, released_payments numeric, refunded_payments numeric,
  failed_payments bigint, audit_events bigint
) language sql stable security definer set search_path=public as $$
select
 (select count(*) from public.reports where status in ('open','investigating')),
 (select count(*) from public.disputes where status in ('open','investigating')),
 (select count(*) from public.withdrawal_requests where status in ('pending','processing')),
 coalesce((select sum(amount) from public.service_requests where payment_status='held'),0),
 coalesce((select sum(amount) from public.service_requests where payment_status='released'),0),
 coalesce((select sum(amount) from public.service_requests where payment_status='refunded'),0),
 (select count(*) from public.payment_orders where status in ('failed','cancelled')),
 (select count(*) from public.admin_audit_log);
$$;
revoke all on function public.admin_ops_summary() from public, anon;
grant execute on function public.admin_ops_summary() to authenticated;

create or replace function public.admin_recent_audit(p_limit integer default 30)
returns table(id bigint, actor_id uuid, action text, entity_type text, entity_id text, metadata jsonb, created_at timestamptz)
language sql stable security definer set search_path=public as $$
select id,actor_id,action,entity_type,entity_id,metadata,created_at
from public.admin_audit_log where public.is_admin() order by created_at desc limit greatest(1,least(p_limit,100));
$$;
revoke all on function public.admin_recent_audit(integer) from public, anon;
grant execute on function public.admin_recent_audit(integer) to authenticated;

create or replace function public.audit_sensitive_changes() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  perform public.write_admin_audit(TG_OP, TG_TABLE_NAME,
    coalesce(to_jsonb(NEW)->>'id',to_jsonb(OLD)->>'id'),
    jsonb_build_object('status',coalesce(to_jsonb(NEW)->>'status',to_jsonb(OLD)->>'status'),
                       'payment_status',coalesce(to_jsonb(NEW)->>'payment_status',to_jsonb(OLD)->>'payment_status')));
  return coalesce(NEW,OLD);
end; $$;

drop trigger if exists audit_service_requests on public.service_requests;
create trigger audit_service_requests after insert or update or delete on public.service_requests for each row execute function public.audit_sensitive_changes();
drop trigger if exists audit_payment_orders on public.payment_orders;
create trigger audit_payment_orders after insert or update or delete on public.payment_orders for each row execute function public.audit_sensitive_changes();
drop trigger if exists audit_withdrawals on public.withdrawal_requests;
create trigger audit_withdrawals after insert or update or delete on public.withdrawal_requests for each row execute function public.audit_sensitive_changes();
drop trigger if exists audit_disputes on public.disputes;
create trigger audit_disputes after insert or update or delete on public.disputes for each row execute function public.audit_sensitive_changes();
drop trigger if exists audit_reports on public.reports;
create trigger audit_reports after insert or update or delete on public.reports for each row execute function public.audit_sensitive_changes();

-- V11.0: Production Guardrails — idempotency, health checks, and critical-event alerts
create table if not exists public.platform_alerts (
  id bigint generated by default as identity primary key,
  severity text not null check (severity in ('info','warning','critical')),
  code text not null,
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);
alter table public.platform_alerts enable row level security;
drop policy if exists "platform alerts admin read" on public.platform_alerts;
create policy "platform alerts admin read" on public.platform_alerts for select using (public.is_admin());
revoke all on public.platform_alerts from anon, authenticated;
grant select on public.platform_alerts to authenticated;

alter table public.payment_orders add column if not exists idempotency_key text;
create unique index if not exists payment_orders_idempotency_key_uidx on public.payment_orders(user_id,idempotency_key) where idempotency_key is not null;

create or replace function public.create_payment_order(p_request_id bigint, p_coupon_code text default null, p_idempotency_key text default null)
returns bigint language plpgsql security definer set search_path = public
as $$
declare r public.service_requests; total numeric; discount numeric := 0; oid bigint; existing bigint;
begin
  if p_idempotency_key is not null and length(trim(p_idempotency_key)) > 120 then raise exception 'invalid idempotency key'; end if;
  if p_idempotency_key is not null then
    select id into existing from public.payment_orders where user_id=auth.uid() and idempotency_key=trim(p_idempotency_key) limit 1;
    if existing is not null then return existing; end if;
  end if;
  select * into r from public.service_requests where id=p_request_id and user_id=auth.uid() for update;
  if not found then raise exception 'الطلب غير موجود'; end if;
  if r.provider_id is null then raise exception 'الطلب غير مرتبط بمقدم خدمة'; end if;
  if r.payment_status in ('held','released') then raise exception 'الطلب مدفوع بالفعل'; end if;
  total := coalesce(r.provider_price,0) + coalesce(r.platform_fee,0);
  if total <= 0 then raise exception 'قيمة الدفع غير صحيحة'; end if;
  if p_coupon_code is not null and length(trim(p_coupon_code)) > 0 then
    select coalesce(discount,0) into discount from public.validate_coupon(upper(trim(p_coupon_code)), coalesce(r.provider_price,0)) limit 1;
  end if;
  total := greatest(0,total-discount);
  insert into public.payment_orders(request_id,user_id,amount,coupon_code,status,idempotency_key)
  values(p_request_id,auth.uid(),total,nullif(upper(trim(p_coupon_code)),''),'created',nullif(trim(p_idempotency_key),'')) returning id into oid;
  return oid;
exception when unique_violation then
  select id into existing from public.payment_orders where user_id=auth.uid() and idempotency_key=trim(p_idempotency_key) limit 1;
  if existing is not null then return existing; end if;
  raise;
end; $$;
grant execute on function public.create_payment_order(bigint,text,text) to authenticated;
revoke execute on function public.create_payment_order(bigint,text) from authenticated;

create or replace function public.admin_platform_health()
returns table(check_name text, status text, details text)
language sql stable security definer set search_path=public as $$
select * from (values
 ('database','ok','اتصال قاعدة البيانات متاح'),
 ('audit_log',case when to_regclass('public.admin_audit_log') is not null then 'ok' else 'error' end,'سجل التدقيق'),
 ('payment_orders',case when to_regclass('public.payment_orders') is not null then 'ok' else 'error' end,'طلبات الدفع'),
 ('idempotency',case when exists(select 1 from pg_indexes where indexname='payment_orders_idempotency_key_uidx') then 'ok' else 'error' end,'حماية تكرار الدفع'),
 ('alerts',case when to_regclass('public.platform_alerts') is not null then 'ok' else 'error' end,'مركز التنبيهات')
) x(check_name,status,details);
$$;
revoke all on function public.admin_platform_health() from public,anon;
grant execute on function public.admin_platform_health() to authenticated;

create or replace function public.admin_recent_alerts(p_limit integer default 30)
returns table(id bigint,severity text,code text,message text,metadata jsonb,resolved_at timestamptz,created_at timestamptz)
language sql stable security definer set search_path=public as $$
select id,severity,code,message,metadata,resolved_at,created_at from public.platform_alerts
where public.is_admin() order by created_at desc limit greatest(1,least(p_limit,100));
$$;
revoke all on function public.admin_recent_alerts(integer) from public,anon;
grant execute on function public.admin_recent_alerts(integer) to authenticated;


-- V12: التشغيل التجاري — العمولات والاشتراكات وسجل الإيرادات
create table if not exists public.commission_ledger (
  id bigint generated by default as identity primary key,
  request_id bigint unique references public.service_requests(id) on delete set null,
  provider_id bigint references public.providers(id) on delete set null,
  gross_amount numeric(12,2) not null check (gross_amount >= 0),
  commission_amount numeric(12,2) not null check (commission_amount >= 0),
  provider_net numeric(12,2) not null check (provider_net >= 0),
  status text not null default 'pending' check (status in ('pending','posted','reversed')),
  created_at timestamptz not null default now()
);
alter table public.commission_ledger enable row level security;
drop policy if exists "commission admin read" on public.commission_ledger;
create policy "commission admin read" on public.commission_ledger for select using (public.is_admin());

create table if not exists public.provider_subscriptions (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references public.providers(id) on delete cascade,
  plan text not null check (plan in ('free','pro','business')),
  status text not null default 'active' check (status in ('active','paused','cancelled')),
  started_at timestamptz not null default now(),
  expires_at timestamptz,
  created_at timestamptz not null default now()
);
alter table public.provider_subscriptions enable row level security;
drop policy if exists "subscriptions own read" on public.provider_subscriptions;
create policy "subscriptions own read" on public.provider_subscriptions
for select using (
  exists(select 1 from public.providers p where p.id=provider_id and p.user_id=auth.uid())
  or public.is_admin()
);

create table if not exists public.platform_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  actor_id uuid references auth.users(id) on delete set null,
  request_id bigint references public.service_requests(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.platform_events enable row level security;
drop policy if exists "events admin read" on public.platform_events;
create policy "events admin read" on public.platform_events for select using (public.is_admin());

create or replace function public.request_withdrawal(p_amount numeric, p_method text default 'واتساب للتواصل')
returns bigint language plpgsql security definer set search_path=public
as $$
declare wid bigint; bal numeric;
begin
  if auth.uid() is null then raise exception 'غير مصرح'; end if;
  if p_amount <= 0 then raise exception 'قيمة السحب غير صحيحة'; end if;
  select balance into bal from public.wallet_accounts where user_id=auth.uid() for update;
  if coalesce(bal,0) < p_amount then raise exception 'الرصيد غير كافٍ'; end if;
  update public.wallet_accounts set balance=balance-p_amount, updated_at=now() where user_id=auth.uid();
  insert into public.withdrawal_requests(user_id,amount,method) values(auth.uid(),p_amount,p_method) returning id into wid;
  insert into public.wallet_transactions(user_id,type,amount,note) values(auth.uid(),'withdrawal',-p_amount,'طلب سحب #'||wid);
  return wid;
end; $$;
grant execute on function public.request_withdrawal(numeric,text) to authenticated;

create or replace function public.get_platform_metrics()
returns table(
  total_requests bigint,
  completed_requests bigint,
  held_amount numeric,
  released_amount numeric,
  pending_withdrawals bigint,
  open_withdrawal_amount numeric,
  platform_fees numeric
) language sql security definer set search_path=public
as $$
  select
    (select count(*) from public.service_requests),
    (select count(*) from public.service_requests where status='تم التنفيذ'),
    coalesce((select sum(provider_price) from public.service_requests where payment_status='held'),0),
    coalesce((select sum(provider_price) from public.service_requests where payment_status='released'),0),
    (select count(*) from public.withdrawal_requests where status='قيد المراجعة'),
    coalesce((select sum(amount) from public.withdrawal_requests where status='قيد المراجعة'),0),
    coalesce((select sum(platform_fee) from public.service_requests where payment_status='released'),0)
  where public.is_admin();
$$;
grant execute on function public.get_platform_metrics() to authenticated;
