-- خدماتي V2.1 — مخطط Supabase الآمن
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  phone text unique not null,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.service_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  service text not null,
  note text not null,
  status text not null default 'قيد المراجعة' check (status in ('قيد المراجعة','جاري التنفيذ','تم التنفيذ','ملغي')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.service_requests enable row level security;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;

-- مهم: المستخدم يستطيع إنشاء ملفه، لكنه لا يستطيع تعديل الدور أو رقم الهاتف.
drop policy if exists "profiles own read" on public.profiles;
drop policy if exists "profiles own insert" on public.profiles;
drop policy if exists "profiles own update" on public.profiles;
drop policy if exists "profiles admin read" on public.profiles;
create policy "profiles own read" on public.profiles for select using (id = auth.uid() or public.is_admin());
create policy "profiles own insert" on public.profiles for insert with check (id = auth.uid() and role = 'user');
create policy "profiles own update name only" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid() and role = 'user' and phone = (select p.phone from public.profiles p where p.id = auth.uid()));

-- الطلبات: المستخدم يرى ويضيف طلباته فقط، والإدارة ترى وتغير الحالة.
drop policy if exists "requests own read" on public.service_requests;
drop policy if exists "requests own insert" on public.service_requests;
drop policy if exists "admin update requests" on public.service_requests;
create policy "requests own read" on public.service_requests for select using (user_id = auth.uid() or public.is_admin());
create policy "requests own insert" on public.service_requests for insert with check (user_id = auth.uid());
create policy "admin update requests" on public.service_requests for update using (public.is_admin()) with check (public.is_admin());

-- بعد إنشاء حسابك، نفّذ هذا الأمر مرة واحدة لتحويله إلى مدير:
-- update public.profiles set role='admin' where phone='01xxxxxxxxx';

-- V2.2: سوق مقدمي الخدمات
create table if not exists public.providers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  category text not null,
  description text not null,
  price numeric(12,2) not null check (price >= 0),
  contact text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.providers enable row level security;

alter table public.service_requests add column if not exists provider_id bigint references public.providers(id) on delete set null;

 drop policy if exists "providers public read active" on public.providers;
 drop policy if exists "providers own insert" on public.providers;
 drop policy if exists "providers own update" on public.providers;
create policy "providers public read active" on public.providers for select using (active = true or user_id = auth.uid() or public.is_admin());
create policy "providers own insert" on public.providers for insert with check (user_id = auth.uid());
create policy "providers own update" on public.providers for update using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());

 drop policy if exists "requests own read" on public.service_requests;
create policy "requests own read" on public.service_requests for select using (user_id = auth.uid() or public.is_admin());

-- V2.3: ملفات مقدمي الخدمات + التقييمات + تتبع العمولة
alter table public.providers add column if not exists commission_rate numeric(5,2) not null default 10 check (commission_rate >= 0 and commission_rate <= 100);
alter table public.service_requests add column if not exists provider_price numeric(12,2);
alter table public.service_requests add column if not exists platform_fee numeric(12,2) not null default 0;

create table if not exists public.provider_reviews (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references public.providers(id) on delete cascade,
  request_id bigint not null unique references public.service_requests(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now()
);
alter table public.provider_reviews enable row level security;
drop policy if exists "reviews public read" on public.provider_reviews;
drop policy if exists "reviews own insert" on public.provider_reviews;
create policy "reviews public read" on public.provider_reviews for select using (true);
create policy "reviews own insert" on public.provider_reviews for insert with check (
  user_id = auth.uid() and exists (
    select 1 from public.service_requests r
    where r.id = request_id and r.user_id = auth.uid() and r.provider_id = provider_id and r.status = 'تم التنفيذ'
  )
);

create or replace function public.get_provider_stats(p_provider_id bigint)
returns table(completed bigint, reviews bigint, average numeric)
language sql stable security definer set search_path = public
as $$
  select
    (select count(*) from public.service_requests r where r.provider_id = p_provider_id and r.status='تم التنفيذ'),
    (select count(*) from public.provider_reviews v where v.provider_id = p_provider_id),
    coalesce((select round(avg(v.rating)::numeric,1) from public.provider_reviews v where v.provider_id = p_provider_id),0);
$$;

grant execute on function public.get_provider_stats(bigint) to anon, authenticated;

-- V3.0: المحفظة + الدفع الداخلي التجريبي + أرباح مقدمي الخدمات
alter table public.service_requests add column if not exists payment_status text not null default 'not_required' check (payment_status in ('not_required','pending','paid','refunded'));
alter table public.service_requests add column if not exists provider_net numeric(12,2) not null default 0;

create table if not exists public.wallet_accounts (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  balance numeric(12,2) not null default 0 check (balance >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.wallet_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('deposit','payment','earning','withdrawal','refund','fee')),
  amount numeric(12,2) not null,
  request_id bigint references public.service_requests(id) on delete set null,
  note text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.withdrawal_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(12,2) not null check (amount > 0),
  method text not null default 'واتساب للتواصل',
  status text not null default 'قيد المراجعة' check (status in ('قيد المراجعة','تم التحويل','مرفوض')),
  created_at timestamptz not null default now()
);

alter table public.wallet_accounts enable row level security;
alter table public.wallet_transactions enable row level security;
alter table public.withdrawal_requests enable row level security;

drop policy if exists "wallet own read" on public.wallet_accounts;
drop policy if exists "wallet own insert" on public.wallet_accounts;
create policy "wallet own read" on public.wallet_accounts for select using (user_id = auth.uid() or public.is_admin());
create policy "wallet own insert" on public.wallet_accounts for insert with check (user_id = auth.uid());

drop policy if exists "wallet tx own read" on public.wallet_transactions;
create policy "wallet tx own read" on public.wallet_transactions for select using (user_id = auth.uid() or public.is_admin());

drop policy if exists "withdraw own read" on public.withdrawal_requests;
drop policy if exists "withdraw own insert" on public.withdrawal_requests;
create policy "withdraw own read" on public.withdrawal_requests for select using (user_id = auth.uid() or public.is_admin());
create policy "withdraw own insert" on public.withdrawal_requests for insert with check (user_id = auth.uid());

create or replace function public.pay_for_request(p_request_id bigint)
returns boolean language plpgsql security definer set search_path = public
as $$
declare r public.service_requests; bal numeric; total numeric;
begin
  select * into r from public.service_requests where id=p_request_id and user_id=auth.uid() for update;
  if not found then raise exception 'الطلب غير موجود'; end if;
  if r.provider_id is null then raise exception 'هذا الطلب لا يحتاج دفعاً'; end if;
  if r.payment_status='paid' then return true; end if;
  total := coalesce(r.provider_price,0);
  if total <= 0 then raise exception 'سعر الطلب غير صحيح'; end if;
  insert into public.wallet_accounts(user_id,balance) values(auth.uid(),0) on conflict(user_id) do nothing;
  select balance into bal from public.wallet_accounts where user_id=auth.uid() for update;
  if bal < total then raise exception 'الرصيد غير كافٍ'; end if;
  update public.wallet_accounts set balance=balance-total,updated_at=now() where user_id=auth.uid();
  insert into public.wallet_transactions(user_id,type,amount,request_id,note) values(auth.uid(),'payment',-total,p_request_id,'دفع الطلب #'||p_request_id);
  update public.service_requests set payment_status='paid' where id=p_request_id;
  if r.provider_id is not null then
    update public.wallet_accounts wa set balance=wa.balance+coalesce(r.provider_net,0),updated_at=now()
    from public.providers p where p.id=r.provider_id and wa.user_id=p.user_id;
    insert into public.wallet_transactions(user_id,type,amount,request_id,note)
    select p.user_id,'earning',coalesce(r.provider_net,0),p_request_id,'أرباح الطلب #'||p_request_id
    from public.providers p where p.id=r.provider_id;
  end if;
  return true;
end; $$;
grant execute on function public.pay_for_request(bigint) to authenticated;

-- للشحن الحقيقي لاحقاً: لا تُضاف أموال حقيقية من الواجهة. يتم ربط بوابة دفع ثم استدعاء خادم آمن.
