-- خدماتي V2.1 — مخطط Supabase الآمن
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  phone text unique not null,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.service_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  service text not null,
  note text not null,
  status text not null default 'قيد المراجعة' check (status in ('قيد المراجعة','جاري التنفيذ','تم التنفيذ','ملغي')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.service_requests enable row level security;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;

-- مهم: المستخدم يستطيع إنشاء ملفه، لكنه لا يستطيع تعديل الدور أو رقم الهاتف.
drop policy if exists "profiles own read" on public.profiles;
drop policy if exists "profiles own insert" on public.profiles;
drop policy if exists "profiles own update" on public.profiles;
drop policy if exists "profiles admin read" on public.profiles;
create policy "profiles own read" on public.profiles for select using (id = auth.uid() or public.is_admin());
create policy "profiles own insert" on public.profiles for insert with check (id = auth.uid() and role = 'user');
create policy "profiles own update name only" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid() and role = 'user' and phone = (select p.phone from public.profiles p where p.id = auth.uid()));

-- الطلبات: المستخدم يرى ويضيف طلباته فقط، والإدارة ترى وتغير الحالة.
drop policy if exists "requests own read" on public.service_requests;
drop policy if exists "requests own insert" on public.service_requests;
drop policy if exists "admin update requests" on public.service_requests;
create policy "requests own read" on public.service_requests for select using (user_id = auth.uid() or public.is_admin());
create policy "requests own insert" on public.service_requests for insert with check (user_id = auth.uid());
create policy "admin update requests" on public.service_requests for update using (public.is_admin()) with check (public.is_admin());

-- بعد إنشاء حسابك، نفّذ هذا الأمر مرة واحدة لتحويله إلى مدير:
-- update public.profiles set role='admin' where phone='01xxxxxxxxx';

-- V2.2: سوق مقدمي الخدمات
create table if not exists public.providers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  category text not null,
  description text not null,
  price numeric(12,2) not null check (price >= 0),
  contact text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.providers enable row level security;

alter table public.service_requests add column if not exists provider_id bigint references public.providers(id) on delete set null;

 drop policy if exists "providers public read active" on public.providers;
 drop policy if exists "providers own insert" on public.providers;
 drop policy if exists "providers own update" on public.providers;
create policy "providers public read active" on public.providers for select using (active = true or user_id = auth.uid() or public.is_admin());
create policy "providers own insert" on public.providers for insert with check (user_id = auth.uid());
create policy "providers own update" on public.providers for update using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());

 drop policy if exists "requests own read" on public.service_requests;
create policy "requests own read" on public.service_requests for select using (user_id = auth.uid() or public.is_admin());
