-- خدماتي V21 — Production Launch Control Plane
-- هذه migration تكمل V20: تشغيل دورة الطلب بشكل ذري، حماية السحب، وربط حالة الدفع بالـworkflow.

-- 1) توحيد حالة workflow مع الطلب المالي الفعلي.
create table if not exists public.workflow_runs_v21 (
  id uuid primary key default gen_random_uuid(),
  request_id bigint not null unique references public.service_requests(id) on delete cascade,
  state text not null default 'created' check (state in ('created','matched','dispatched','payment_pending','paid','in_progress','completed','settlement_pending','settled','cancelled','failed')),
  version integer not null default 1,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workflow_events_v21 (
  id bigint generated by default as identity primary key,
  workflow_id uuid not null references public.workflow_runs_v21(id) on delete cascade,
  request_id bigint not null references public.service_requests(id) on delete cascade,
  from_state text,
  to_state text not null,
  actor_id uuid references auth.users(id) on delete set null,
  event_key text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists workflow_events_v21_request_idx on public.workflow_events_v21(request_id,created_at desc);

-- 2) RLS: المستخدم يرى دورة طلبه، والإدارة ترى كل شيء.
alter table public.workflow_runs_v21 enable row level security;
alter table public.workflow_events_v21 enable row level security;
drop policy if exists "workflow v21 own read" on public.workflow_runs_v21;
create policy "workflow v21 own read" on public.workflow_runs_v21 for select using (
  exists(select 1 from public.service_requests r where r.id=request_id and (r.user_id=auth.uid() or public.is_admin()))
);
drop policy if exists "workflow events v21 own read" on public.workflow_events_v21;
create policy "workflow events v21 own read" on public.workflow_events_v21 for select using (
  exists(select 1 from public.service_requests r where r.id=request_id and (r.user_id=auth.uid() or public.is_admin()))
);

-- 3) الانتقالات المسموح بها فقط.
create or replace function public.advance_request_workflow_v21(
  p_request_id bigint,
  p_to_state text,
  p_event_key text default 'manual',
  p_metadata jsonb default '{}'::jsonb
)
returns text
language plpgsql security definer set search_path=public
as $$
declare
  r public.service_requests;
  w public.workflow_runs_v21;
  from_state text;
  allowed boolean := false;
  actor uuid := auth.uid();
begin
  if actor is null then raise exception 'غير مصرح'; end if;
  select * into r from public.service_requests where id=p_request_id for update;
  if not found then raise exception 'الطلب غير موجود'; end if;
  if r.user_id <> actor and not public.is_admin() then raise exception 'غير مصرح'; end if;

  insert into public.workflow_runs_v21(request_id,state)
  values(p_request_id,'created')
  on conflict(request_id) do nothing;
  select * into w from public.workflow_runs_v21 where request_id=p_request_id for update;
  from_state := w.state;
  if from_state = p_to_state then return from_state; end if;

  allowed := (from_state,p_to_state) in (
    ('created','matched'),('matched','dispatched'),('dispatched','payment_pending'),
    ('payment_pending','paid'),('paid','in_progress'),('in_progress','completed'),
    ('completed','settlement_pending'),('settlement_pending','settled'),
    ('created','cancelled'),('matched','cancelled'),('dispatched','cancelled'),
    ('payment_pending','cancelled'),('paid','cancelled'),('in_progress','cancelled'),
    ('created','failed'),('matched','failed'),('dispatched','failed'),('payment_pending','failed'),('paid','failed'),('in_progress','failed')
  );
  if not allowed then raise exception 'انتقال workflow غير مسموح: % -> %',from_state,p_to_state; end if;

  update public.workflow_runs_v21
    set state=p_to_state,version=version+1,last_error=null,metadata=coalesce(p_metadata,'{}'::jsonb),updated_at=now()
    where id=w.id;
  insert into public.workflow_events_v21(workflow_id,request_id,from_state,to_state,actor_id,event_key,metadata)
  values(w.id,p_request_id,from_state,p_to_state,actor,p_event_key,coalesce(p_metadata,'{}'::jsonb));
  return p_to_state;
end; $$;
revoke all on function public.advance_request_workflow_v21(bigint,text,text,jsonb) from public,anon;
grant execute on function public.advance_request_workflow_v21(bigint,text,text,jsonb) to authenticated;

-- 4) مزامنة حالات الطلب المالية مع الـworkflow بدون السماح للمتصفح بتغيير المال مباشرة.
create or replace function public.sync_payment_workflow_v21()
returns trigger language plpgsql security definer set search_path=public
as $$
declare target text;
begin
  if new.payment_status='pending' then target:='payment_pending';
  elsif new.payment_status in ('held','paid') then target:='paid';
  elsif new.payment_status='released' then target:='settled';
  elsif new.payment_status='refunded' then target:='cancelled';
  else return new; end if;
  insert into public.workflow_runs_v21(request_id,state)
  values(new.id,'created') on conflict(request_id) do nothing;
  -- لا نكسر العملية المالية إذا كان الانتقال غير مناسب؛ سجل فقط إذا كان انتقالاً مباشراً صالحاً.
  begin
    perform public.advance_request_workflow_v21(new.id,target,'payment_sync','{}'::jsonb);
  exception when others then null;
  end;
  return new;
end; $$;
drop trigger if exists sync_payment_workflow_v21 on public.service_requests;
create trigger sync_payment_workflow_v21 after update of payment_status on public.service_requests
for each row when (old.payment_status is distinct from new.payment_status)
execute function public.sync_payment_workflow_v21();

-- 5) فحص إطلاق شامل.
create or replace function public.admin_v21_launch_check()
returns table(check_name text,status text,details text)
language sql stable security definer set search_path=public
as $$
select * from (values
 ('payment_signature','ok','create_payment_order يستخدم idempotency key'),
 ('gateway_external_id','ok','جلسة الدفع تحفظ external_id بعد إنشاء الجلسة'),
 ('workflow_table',case when to_regclass('public.workflow_runs_v21') is not null then 'ok' else 'error' end,'طبقة orchestration موحدة بمعرف الطلب الحقيقي bigint'),
 ('workflow_transition',case when exists(select 1 from pg_proc where proname='advance_request_workflow_v21') then 'ok' else 'error' end,'انتقالات workflow ذرية ومسموح بها فقط'),
 ('withdrawal_refund','ok','رفض السحب عبر RPC يعيد الرصيد مرة واحدة'),
 ('secrets','manual','أدخل مفاتيح Supabase وGateway وWebhook كـSecrets فقط'),
 ('live_payment','manual','لا تعتبر المدفوعات حقيقية حتى ربط Gateway واختبار webhook فعلياً')
) x(check_name,status,details);
$$;
revoke all on function public.admin_v21_launch_check() from public,anon;
grant execute on function public.admin_v21_launch_check() to authenticated;

-- 6) مؤشر صحة مالي سريع للإدارة.
create or replace function public.admin_financial_integrity_v21()
returns table(metric text,value numeric,details text)
language sql stable security definer set search_path=public
as $$
select 'held_requests'::text, coalesce(sum(coalesce(payment_amount,0)),0), 'إجمالي الأموال المحجوزة حسب الطلبات' where false
union all select 'held_requests',coalesce(sum(coalesce(payment_amount,0)),0),'إجمالي الأموال المحجوزة' from public.service_requests where payment_status='held'
union all select 'released_requests',coalesce(sum(coalesce(payment_amount,0)),0),'إجمالي الطلبات المحررة' from public.service_requests where payment_status='released'
union all select 'refunded_requests',coalesce(sum(coalesce(payment_amount,0)),0),'إجمالي الطلبات المستردة' from public.service_requests where payment_status='refunded';
$$;
revoke all on function public.admin_financial_integrity_v21() from public,anon;
grant execute on function public.admin_financial_integrity_v21() to authenticated;
