-- خدماتي V22 — Financial Ledger + Webhook Idempotency + Reconciliation
-- القفزة التالية: كل عملية مالية مهمة لها أثر محاسبي قابل للمراجعة، والـWebhook لا يعالج نفس الحدث مرتين.
-- نفّذ بعد V21 وبعد Backup لقاعدة البيانات.

-- 1) سجل أحداث الـWebhook لمنع إعادة تنفيذ نفس الحدث.
create table if not exists public.payment_webhook_events_v22 (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  external_id text,
  status text not null,
  amount numeric(12,2),
  payload_hash text,
  processed boolean not null default false,
  error_message text,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);
create index if not exists payment_webhook_events_v22_external_idx on public.payment_webhook_events_v22(external_id);
alter table public.payment_webhook_events_v22 enable row level security;

-- 2) دفتر إيرادات المنصة: العمولة لا تختفي من الحسابات.
create table if not exists public.platform_finance_ledger_v22 (
  id bigint generated by default as identity primary key,
  request_id bigint not null unique references public.service_requests(id) on delete cascade,
  payment_order_id bigint references public.payment_orders(id) on delete set null,
  gross_customer_amount numeric(12,2) not null default 0,
  provider_amount numeric(12,2) not null default 0,
  platform_fee numeric(12,2) not null default 0,
  status text not null default 'pending' check (status in ('pending','posted','refunded','void')),
  created_at timestamptz not null default now(),
  posted_at timestamptz
);
create index if not exists platform_finance_ledger_v22_status_idx on public.platform_finance_ledger_v22(status,created_at desc);
alter table public.platform_finance_ledger_v22 enable row level security;

-- 3) Webhook ذريّ idempotent: الحدث نفسه يعاد بلا أثر مالي إضافي.
create or replace function public.confirm_payment_webhook_v22(
  p_external_id text,
  p_status text,
  p_amount numeric,
  p_event_id text
)
returns boolean
language plpgsql security definer set search_path=public
as $$
declare
  o public.payment_orders;
  ev public.payment_webhook_events_v22;
  normalized text := lower(trim(coalesce(p_status,'')));
begin
  if nullif(trim(p_event_id),'') is null then raise exception 'event_id مطلوب'; end if;
  if normalized not in ('paid','failed','refunded') then raise exception 'حالة webhook غير مدعومة'; end if;

  insert into public.payment_webhook_events_v22(event_id,external_id,status,amount,processed)
  values(trim(p_event_id),nullif(trim(p_external_id),''),normalized,p_amount,false)
  on conflict(event_id) do nothing;
  select * into ev from public.payment_webhook_events_v22 where event_id=trim(p_event_id) for update;
  if ev.processed then return true; end if;

  select * into o from public.payment_orders where external_id=trim(p_external_id) for update;
  if not found then
    update public.payment_webhook_events_v22 set error_message='payment order not found' where id=ev.id;
    raise exception 'payment order not found';
  end if;
  if abs(coalesce(o.amount,0)-coalesce(p_amount,0)) > 0.01 then
    update public.payment_webhook_events_v22 set error_message='amount mismatch' where id=ev.id;
    raise exception 'amount mismatch';
  end if;

  if normalized='paid' then
    update public.payment_orders set status='paid',paid_at=coalesce(paid_at,now()) where id=o.id;
    update public.service_requests
      set payment_status='held',payment_amount=o.amount
      where id=o.request_id and user_id=o.user_id and payment_status in ('pending','not_required');
    if not exists (select 1 from public.wallet_transactions where user_id=o.user_id and request_id=o.request_id and type='payment' and amount < 0 and note like 'دفع مؤكد عبر بوابة الدفع%') then
      insert into public.wallet_transactions(user_id,type,amount,request_id,note) values(o.user_id,'payment',-o.amount,o.request_id,'دفع مؤكد عبر بوابة الدفع');
    end if;
  elsif normalized in ('failed','refunded') then
    update public.payment_orders set status=normalized where id=o.id;
    update public.service_requests set payment_status='not_required' where id=o.request_id and payment_status='pending';
  end if;

  update public.payment_webhook_events_v22 set processed=true,processed_at=now(),error_message=null where id=ev.id;
  return true;
end; $$;
revoke all on function public.confirm_payment_webhook_v22(text,text,numeric,text) from public,anon,authenticated;
grant execute on function public.confirm_payment_webhook_v22(text,text,numeric,text) to service_role;

-- 4) التسوية تسجل حصة المنصة صراحةً، مع منع التكرار.
create or replace function public.post_platform_finance_v22(p_request_id bigint)
returns boolean language plpgsql security definer set search_path=public
as $$
declare r public.service_requests; po public.payment_orders; total numeric; fee numeric; provider numeric;
begin
  if not public.is_admin() and auth.uid() is null then raise exception 'غير مصرح'; end if;
  select * into r from public.service_requests where id=p_request_id for update;
  if not found then raise exception 'الطلب غير موجود'; end if;
  if r.payment_status <> 'released' then raise exception 'الطلب غير مسوى'; end if;
  total:=greatest(coalesce(r.payment_amount,coalesce(r.provider_price,0)+coalesce(r.platform_fee,0)),0);
  fee:=greatest(coalesce(r.platform_fee,0),0);
  provider:=greatest(coalesce(r.provider_price,0),0);
  select * into po from public.payment_orders where request_id=p_request_id and status='paid' order by id desc limit 1;
  insert into public.platform_finance_ledger_v22(request_id,payment_order_id,gross_customer_amount,provider_amount,platform_fee,status,posted_at)
  values(p_request_id,po.id,total,provider,fee,'posted',now())
  on conflict(request_id) do update set payment_order_id=excluded.payment_order_id,gross_customer_amount=excluded.gross_customer_amount,provider_amount=excluded.provider_amount,platform_fee=excluded.platform_fee,status='posted',posted_at=coalesce(public.platform_finance_ledger_v22.posted_at,excluded.posted_at);
  return true;
end; $$;
revoke all on function public.post_platform_finance_v22(bigint) from public,anon;
grant execute on function public.post_platform_finance_v22(bigint) to authenticated;

-- 5) مطابقة مالية: تكشف الطلبات التي حالتها لا تتطابق مع أوامر الدفع أو دفتر المنصة.
create or replace function public.admin_v22_reconciliation()
returns table(request_id bigint, payment_status text, payment_order_status text, order_amount numeric, request_amount numeric, ledger_status text, issue text)
language sql stable security definer set search_path=public
as $$
select r.id,r.payment_status,po.status,po.amount,r.payment_amount,pl.status,
case
 when r.payment_status in ('held','released') and po.id is null then 'طلب مدفوع بلا أمر دفع'
 when r.payment_status='held' and coalesce(po.status,'')<>'paid' then 'الطلب محجوز لكن أمر الدفع ليس paid'
 when r.payment_status='released' and pl.id is null then 'تمت التسوية بدون سجل إيراد منصة'
 when r.payment_status='released' and abs(coalesce(pl.gross_customer_amount,0)-coalesce(r.payment_amount,0))>0.01 then 'اختلاف قيمة العميل'
 when r.payment_status='released' and abs(coalesce(pl.provider_amount,0)-coalesce(r.provider_price,0))>0.01 then 'اختلاف حصة مقدم الخدمة'
 when r.payment_status='released' and abs(coalesce(pl.platform_fee,0)-coalesce(r.platform_fee,0))>0.01 then 'اختلاف عمولة المنصة'
 else null end
from public.service_requests r
left join lateral (select * from public.payment_orders x where x.request_id=r.id order by x.id desc limit 1) po on true
left join public.platform_finance_ledger_v22 pl on pl.request_id=r.id
where public.is_admin() and (
 (r.payment_status in ('held','released') and po.id is null) or
 (r.payment_status='held' and coalesce(po.status,'')<>'paid') or
 (r.payment_status='released' and pl.id is null) or
 (r.payment_status='released' and abs(coalesce(pl.gross_customer_amount,0)-coalesce(r.payment_amount,0))>0.01) or
 (r.payment_status='released' and abs(coalesce(pl.provider_amount,0)-coalesce(r.provider_price,0))>0.01) or
 (r.payment_status='released' and abs(coalesce(pl.platform_fee,0)-coalesce(r.platform_fee,0))>0.01)
)
order by r.id desc;
$$;
revoke all on function public.admin_v22_reconciliation() from public,anon;
grant execute on function public.admin_v22_reconciliation() to authenticated;

-- 6) إدخال سجل المنصة تلقائياً بعد تحرير المبلغ.
create or replace function public.auto_post_platform_finance_v22()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
 if new.payment_status='released' and old.payment_status is distinct from new.payment_status then
   perform public.post_platform_finance_v22(new.id);
 end if;
 return new;
end; $$;
drop trigger if exists auto_post_platform_finance_v22 on public.service_requests;
create trigger auto_post_platform_finance_v22 after update of payment_status on public.service_requests
for each row when (old.payment_status is distinct from new.payment_status)
execute function public.auto_post_platform_finance_v22();

-- 7) فحص إطلاق V22.
create or replace function public.admin_v22_launch_check()
returns table(check_name text,status text,details text)
language sql stable security definer set search_path=public
as $$
select * from (values
 ('webhook_idempotency',case when to_regclass('public.payment_webhook_events_v22') is not null then 'ok' else 'error' end,'منع تكرار نفس webhook event'),
 ('platform_ledger',case when to_regclass('public.platform_finance_ledger_v22') is not null then 'ok' else 'error' end,'كل تسوية لها سجل حصة المنصة'),
 ('reconciliation',case when exists(select 1 from pg_proc where proname='admin_v22_reconciliation') then 'ok' else 'error' end,'كشف اختلافات الطلب/الدفع/العمولة'),
 ('secrets','manual','أدخل أسرار Supabase وGateway في Edge Function Secrets فقط'),
 ('sandbox','manual','اختبر webhook مرتين بنفس event_id وتأكد من عدم تكرار الحركة المالية')
) x(check_name,status,details);
$$;
revoke all on function public.admin_v22_launch_check() from public,anon;
grant execute on function public.admin_v22_launch_check() to authenticated;
