-- خدماتي V23 — Control Tower / Operational Command Center
-- الهدف: شاشة واحدة للإدارة تكشف صحة دورة الطلب والمال والمخاطر والحالات الحساسة.

create table if not exists public.platform_incidents_v23 (
  id bigint generated by default as identity primary key,
  incident_key text not null unique,
  severity text not null check (severity in ('info','warning','critical')),
  title text not null,
  details text,
  source text,
  resolved boolean not null default false,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  resolved_at timestamptz
);
create index if not exists platform_incidents_v23_open_idx on public.platform_incidents_v23(resolved,severity,last_seen_at desc);
alter table public.platform_incidents_v23 enable row level security;
drop policy if exists "v23 admin read incidents" on public.platform_incidents_v23;
create policy "v23 admin read incidents" on public.platform_incidents_v23 for select using (public.is_admin());

create or replace function public.admin_v23_control_tower()
returns table(metric_key text, label text, value numeric, status text, details text)
language plpgsql stable security definer set search_path=public
as $$
declare
  pending_requests numeric;
  active_requests numeric;
  held_amount numeric;
  released_amount numeric;
  failed_payments numeric;
  pending_withdrawals numeric;
  open_reports numeric;
  open_disputes numeric;
  reconciliation_issues numeric;
  workflow_stuck numeric;
  open_incidents numeric;
begin
  if not public.is_admin() then raise exception 'غير مصرح'; end if;
  select count(*) into pending_requests from public.service_requests where status='قيد المراجعة';
  select count(*) into active_requests from public.service_requests where status='جاري التنفيذ';
  select coalesce(sum(coalesce(provider_price,0)),0) into held_amount from public.service_requests where payment_status='held';
  select coalesce(sum(coalesce(provider_price,0)),0) into released_amount from public.service_requests where payment_status='released';
  select count(*) into failed_payments from public.payment_orders where status='failed';
  select count(*) into pending_withdrawals from public.withdrawal_requests where status='قيد المراجعة';
  select count(*) into open_reports from public.reports where status in ('open','investigating');
  select count(*) into open_disputes from public.disputes where status in ('open','investigating');
  begin select count(*) into reconciliation_issues from public.admin_v22_reconciliation(); exception when others then reconciliation_issues:=0; end;
  begin
    select count(*) into workflow_stuck from public.workflow_runs_v21 where state in ('payment_pending','dispatched','in_progress') and updated_at < now() - interval '24 hours';
  exception when undefined_table then workflow_stuck:=0;
  end;
  select count(*) into open_incidents from public.platform_incidents_v23 where not resolved;

  return query values
    ('pending_requests','طلبات قيد المراجعة',pending_requests,case when pending_requests>20 then 'critical' when pending_requests>5 then 'warning' else 'ok' end,'طلبات تحتاج متابعة'),
    ('active_requests','طلبات جاري تنفيذها',active_requests,'ok','طلبات نشطة'),
    ('held_amount','أموال محجوزة',held_amount,case when held_amount>100000 then 'warning' else 'ok' end,'قيمة الأموال المحجوزة'),
    ('released_amount','أموال محررة',released_amount,'ok','إجمالي الأموال المحررة'),
    ('failed_payments','مدفوعات فاشلة',failed_payments,case when failed_payments>10 then 'warning' else 'ok' end,'آخر عدد مسجل في أوامر الدفع'),
    ('pending_withdrawals','طلبات سحب معلقة',pending_withdrawals,case when pending_withdrawals>10 then 'warning' else 'ok' end,'تحتاج مراجعة الإدارة'),
    ('open_reports','بلاغات مفتوحة',open_reports,case when open_reports>10 then 'critical' when open_reports>0 then 'warning' else 'ok' end,'حالات أمان مفتوحة'),
    ('open_disputes','نزاعات مفتوحة',open_disputes,case when open_disputes>10 then 'critical' when open_disputes>0 then 'warning' else 'ok' end,'حالات مالية/تنفيذية مفتوحة'),
    ('reconciliation_issues','مشاكل المطابقة المالية',reconciliation_issues,case when reconciliation_issues>0 then 'critical' else 'ok' end,'يجب التحقيق قبل أي تشغيل مالي واسع'),
    ('workflow_stuck','طلبات عالقة +24 ساعة',workflow_stuck,case when workflow_stuck>0 then 'warning' else 'ok' end,'مبني على workflow V21'),
    ('open_incidents','حوادث منصة مفتوحة',open_incidents,case when open_incidents>0 then 'critical' else 'ok' end,'سجل الحوادث V23');
end; $$;
revoke all on function public.admin_v23_control_tower() from public,anon;
grant execute on function public.admin_v23_control_tower() to authenticated;

create or replace function public.admin_v23_recent_incidents(p_limit integer default 20)
returns table(id bigint,incident_key text,severity text,title text,details text,source text,resolved boolean,last_seen_at timestamptz)
language sql stable security definer set search_path=public
as $$
select id,incident_key,severity,title,details,source,resolved,last_seen_at
from public.platform_incidents_v23
where public.is_admin()
order by resolved asc, case severity when 'critical' then 1 when 'warning' then 2 else 3 end, last_seen_at desc
limit greatest(1,least(coalesce(p_limit,20),100));
$$;
revoke all on function public.admin_v23_recent_incidents(integer) from public,anon;
grant execute on function public.admin_v23_recent_incidents(integer) to authenticated;

create or replace function public.admin_v23_refresh_incident(p_incident_key text,p_severity text,p_title text,p_details text default null,p_source text default null)
returns bigint
language plpgsql security definer set search_path=public
as $$
declare iid bigint;
begin
  if not public.is_admin() then raise exception 'غير مصرح'; end if;
  insert into public.platform_incidents_v23(incident_key,severity,title,details,source,resolved,last_seen_at)
  values(trim(p_incident_key),p_severity,trim(p_title),p_details,p_source,false,now())
  on conflict(incident_key) do update set severity=excluded.severity,title=excluded.title,details=excluded.details,source=excluded.source,last_seen_at=now(),resolved=false,resolved_at=null
  returning id into iid;
  return iid;
end; $$;
revoke all on function public.admin_v23_refresh_incident(text,text,text,text,text) from public,anon;
grant execute on function public.admin_v23_refresh_incident(text,text,text,text,text) to authenticated;

create or replace function public.admin_v23_resolve_incident(p_id bigint)
returns boolean language plpgsql security definer set search_path=public
as $$
begin
  if not public.is_admin() then raise exception 'غير مصرح'; end if;
  update public.platform_incidents_v23 set resolved=true,resolved_at=now() where id=p_id;
  return found;
end; $$;
revoke all on function public.admin_v23_resolve_incident(bigint) from public,anon;
grant execute on function public.admin_v23_resolve_incident(bigint) to authenticated;

create or replace function public.admin_v23_launch_gate()
returns table(gate_key text,label text,pass boolean,details text)
language plpgsql stable security definer set search_path=public
as $$
declare n numeric;
begin
 if not public.is_admin() then raise exception 'غير مصرح'; end if;
 select count(*) into n from public.admin_v22_reconciliation();
 return query values
 ('reconciliation','المطابقة المالية',n=0,case when n=0 then 'لا توجد فروقات مسجلة' else n||' مشكلة تحتاج مراجعة' end),
 ('open_cases','الحالات الحساسة',((select count(*) from public.reports where status in ('open','investigating'))+(select count(*) from public.disputes where status in ('open','investigating')))=0,'يفضل معالجة البلاغات والنزاعات قبل التوسع'),
 ('webhook','حماية Webhook',exists(select 1 from pg_proc where proname='confirm_payment_webhook_v22'),'وظيفة V22 موجودة'),
 ('ledger','دفتر المنصة',exists(select 1 from pg_class where relname='platform_finance_ledger_v22'),'سجل الإيرادات موجود'),
 ('control_tower','مركز التشغيل',true,'V23 Control Tower مثبت');
end; $$;
revoke all on function public.admin_v23_launch_gate() from public,anon;
grant execute on function public.admin_v23_launch_gate() to authenticated;
