-- خدماتي V24 — Controlled Pilot / Kill Switch / Feature Gates
-- الهدف: إطلاق تجريبي آمن مع مفتاح إيقاف فوري وميزات قابلة للتحكم.
-- نفّذ بعد V23 وبعد Backup.

create table if not exists public.platform_control_v24 (
  id boolean primary key default true check (id=true),
  mode text not null default 'pilot' check (mode in ('pilot','live','maintenance','paused')),
  payments_enabled boolean not null default false,
  withdrawals_enabled boolean not null default false,
  new_requests_enabled boolean not null default true,
  dispatch_enabled boolean not null default true,
  reason text,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);
insert into public.platform_control_v24(id) values(true) on conflict(id) do nothing;
alter table public.platform_control_v24 enable row level security;
drop policy if exists "v24 admin read control" on public.platform_control_v24;
create policy "v24 admin read control" on public.platform_control_v24 for select using (public.is_admin());

create table if not exists public.platform_control_audit_v24 (
 id bigint generated by default as identity primary key,
 actor_id uuid references auth.users(id),
 old_mode text, new_mode text,
 payments_enabled boolean, withdrawals_enabled boolean, new_requests_enabled boolean, dispatch_enabled boolean,
 reason text, created_at timestamptz not null default now()
);
alter table public.platform_control_audit_v24 enable row level security;
drop policy if exists "v24 admin read audit" on public.platform_control_audit_v24;
create policy "v24 admin read audit" on public.platform_control_audit_v24 for select using (public.is_admin());

create or replace function public.v24_platform_status()
returns table(mode text,payments_enabled boolean,withdrawals_enabled boolean,new_requests_enabled boolean,dispatch_enabled boolean,reason text,updated_at timestamptz)
language sql stable security definer set search_path=public as $$
 select mode,payments_enabled,withdrawals_enabled,new_requests_enabled,dispatch_enabled,reason,updated_at from public.platform_control_v24 where id=true;
$$;
revoke all on function public.v24_platform_status() from public,anon;
grant execute on function public.v24_platform_status() to authenticated;

create or replace function public.admin_v24_set_platform_control(
 p_mode text, p_payments_enabled boolean, p_withdrawals_enabled boolean,
 p_new_requests_enabled boolean, p_dispatch_enabled boolean, p_reason text default null)
returns boolean language plpgsql security definer set search_path=public as $$
declare old public.platform_control_v24; nm text:=lower(trim(coalesce(p_mode,'')));
begin
 if not public.is_admin() then raise exception 'غير مصرح'; end if;
 if nm not in ('pilot','live','maintenance','paused') then raise exception 'وضع غير صالح'; end if;
 select * into old from public.platform_control_v24 where id=true for update;
 update public.platform_control_v24 set mode=nm,payments_enabled=coalesce(p_payments_enabled,false),withdrawals_enabled=coalesce(p_withdrawals_enabled,false),new_requests_enabled=coalesce(p_new_requests_enabled,false),dispatch_enabled=coalesce(p_dispatch_enabled,false),reason=nullif(trim(p_reason),''),updated_by=auth.uid(),updated_at=now() where id=true;
 insert into public.platform_control_audit_v24(actor_id,old_mode,new_mode,payments_enabled,withdrawals_enabled,new_requests_enabled,dispatch_enabled,reason) values(auth.uid(),old.mode,nm,p_payments_enabled,p_withdrawals_enabled,p_new_requests_enabled,p_dispatch_enabled,p_reason);
 return true;
end; $$;
revoke all on function public.admin_v24_set_platform_control(text,boolean,boolean,boolean,boolean,text) from public,anon;
grant execute on function public.admin_v24_set_platform_control(text,boolean,boolean,boolean,boolean,text) to authenticated;

create or replace function public.admin_v24_recent_control_audit(p_limit integer default 20)
returns table(id bigint,actor_id uuid,old_mode text,new_mode text,payments_enabled boolean,withdrawals_enabled boolean,new_requests_enabled boolean,dispatch_enabled boolean,reason text,created_at timestamptz)
language sql stable security definer set search_path=public as $$
 select id,actor_id,old_mode,new_mode,payments_enabled,withdrawals_enabled,new_requests_enabled,dispatch_enabled,reason,created_at from public.platform_control_audit_v24 where public.is_admin() order by id desc limit greatest(1,least(coalesce(p_limit,20),100));
$$;
revoke all on function public.admin_v24_recent_control_audit(integer) from public,anon;
grant execute on function public.admin_v24_recent_control_audit(integer) to authenticated;

-- Consolidated payment-order function: idempotency + V24 payment gate.
create or replace function public.create_payment_order(p_request_id bigint,p_coupon_code text default null,p_idempotency_key text default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare r public.service_requests; total numeric; discount numeric:=0; oid bigint; k text:=nullif(trim(p_idempotency_key),''); c public.platform_control_v24;
begin
 select * into c from public.platform_control_v24 where id=true;
 if not coalesce(c.payments_enabled,false) then raise exception 'الدفع متوقف حالياً — خدماتي في وضع تجريبي'; end if;
 select * into r from public.service_requests where id=p_request_id and user_id=auth.uid() for update;
 if not found then raise exception 'الطلب غير موجود'; end if;
 if r.provider_id is null then raise exception 'الطلب غير مرتبط بمقدم خدمة'; end if;
 if r.payment_status in ('held','released') then raise exception 'الطلب مدفوع بالفعل'; end if;
 if k is not null then select id into oid from public.payment_orders where idempotency_key=k; if oid is not null then return oid; end if; end if;
 total:=coalesce(r.provider_price,0)+coalesce(r.platform_fee,0);
 if total<=0 then raise exception 'قيمة الدفع غير صحيحة'; end if;
 if p_coupon_code is not null and length(trim(p_coupon_code))>0 then select coalesce(discount,0) into discount from public.validate_coupon(upper(trim(p_coupon_code)),coalesce(r.provider_price,0)) limit 1; end if;
 total:=greatest(0,total-discount);
 insert into public.payment_orders(request_id,user_id,amount,coupon_code,status,idempotency_key) values(p_request_id,auth.uid(),total,nullif(upper(trim(p_coupon_code)),''),'created',k) returning id into oid;
 return oid;
exception when unique_violation then
 select id into oid from public.payment_orders where idempotency_key=k; if oid is null then raise; end if; return oid;
end; $$;
revoke all on function public.create_payment_order(bigint,text) from public,anon,authenticated;
grant execute on function public.create_payment_order(bigint,text,text) to authenticated;

create or replace function public.admin_v24_launch_gate()
returns table(gate_key text,label text,pass boolean,details text)
language plpgsql stable security definer set search_path=public as $$
declare c public.platform_control_v24; n numeric:=0;
begin
 if not public.is_admin() then raise exception 'غير مصرح'; end if;
 select * into c from public.platform_control_v24 where id=true;
 begin select count(*) into n from public.admin_v22_reconciliation(); exception when others then n:=0; end;
 return query values
 ('mode','وضع المنصة',c.mode in ('pilot','live'), 'الوضع الحالي: '||c.mode),
 ('reconciliation','المطابقة المالية',n=0,case when n=0 then 'لا توجد فروقات' else n||' مشكلة' end),
 ('payments','الدفع',c.payments_enabled,case when c.payments_enabled then 'مفعل' else 'متوقف — آمن للتجربة' end),
 ('withdrawals','السحب',c.withdrawals_enabled,case when c.withdrawals_enabled then 'مفعل' else 'متوقف' end),
 ('requests','طلبات جديدة',c.new_requests_enabled,case when c.new_requests_enabled then 'مسموح' else 'متوقف' end),
 ('dispatch','التوزيع',c.dispatch_enabled,case when c.dispatch_enabled then 'مسموح' else 'متوقف' end);
end; $$;
revoke all on function public.admin_v24_launch_gate() from public,anon;
grant execute on function public.admin_v24_launch_gate() to authenticated;
