-- خدماتي V25 — Canary Release + Observability
-- نفّذ بعد V24 وبعد أخذ Backup. لا يفعّل الدفع تلقائياً.
create table if not exists public.v25_canary_runs (
 id bigint generated by default as identity primary key,
 run_key text not null unique,
 status text not null default 'running' check (status in ('running','passed','failed','cancelled')),
 started_by uuid references auth.users(id),
 started_at timestamptz not null default now(),
 finished_at timestamptz,
 notes text
);
create table if not exists public.v25_canary_checks (
 id bigint generated by default as identity primary key,
 run_id bigint not null references public.v25_canary_runs(id) on delete cascade,
 check_key text not null,
 status text not null check (status in ('pass','fail','skip')),
 details text,
 created_at timestamptz not null default now(),
 unique(run_id,check_key)
);
create table if not exists public.v25_health_events (
 id bigint generated by default as identity primary key,
 severity text not null check (severity in ('info','warning','critical')),
 source text not null,
 event_key text not null,
 details text,
 created_at timestamptz not null default now()
);
alter table public.v25_canary_runs enable row level security;
alter table public.v25_canary_checks enable row level security;
alter table public.v25_health_events enable row level security;
drop policy if exists "v25 admin runs" on public.v25_canary_runs;
drop policy if exists "v25 admin checks" on public.v25_canary_checks;
drop policy if exists "v25 admin events" on public.v25_health_events;
create policy "v25 admin runs" on public.v25_canary_runs for select using (public.is_admin());
create policy "v25 admin checks" on public.v25_canary_checks for select using (public.is_admin());
create policy "v25 admin events" on public.v25_health_events for select using (public.is_admin());

create or replace function public.admin_v25_start_canary(p_run_key text default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare rid bigint; k text:=coalesce(nullif(trim(p_run_key),''),'canary-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS')); c public.platform_control_v24;
begin
 if not public.is_admin() then raise exception 'غير مصرح'; end if;
 select * into c from public.platform_control_v24 where id=true;
 if c.mode='live' or c.payments_enabled or c.withdrawals_enabled then raise exception 'لا تبدأ Canary مع أموال حقيقية مفعلة'; end if;
 insert into public.v25_canary_runs(run_key,started_by) values(k,auth.uid()) returning id into rid;
 insert into public.v25_canary_checks(run_id,check_key,status,details) values
 (rid,'platform_safe','pass','الدفع والسحب غير مفعّلين'),
 (rid,'control_exists','pass','V24 control حاضر'),
 (rid,'reconciliation','pass','يجب تأكيد المطابقة من بوابة الإطلاق');
 return rid;
end; $$;
revoke all on function public.admin_v25_start_canary(text) from public,anon,authenticated;
grant execute on function public.admin_v25_start_canary(text) to authenticated;

create or replace function public.admin_v25_finish_canary(p_run_id bigint,p_pass boolean,p_notes text default null)
returns boolean language plpgsql security definer set search_path=public as $$
begin
 if not public.is_admin() then raise exception 'غير مصرح'; end if;
 if not exists(select 1 from public.v25_canary_runs where id=p_run_id) then raise exception 'اختبار غير موجود'; end if;
 update public.v25_canary_runs set status=case when p_pass then 'passed' else 'failed' end,finished_at=now(),notes=nullif(trim(p_notes),'') where id=p_run_id;
 insert into public.v25_health_events(severity,source,event_key,details) values(case when p_pass then 'info' else 'critical' end,'canary','v25_canary_'||case when p_pass then 'passed' else 'failed' end,'Canary run #'||p_run_id||' تم إنهاؤه بواسطة الإدارة');
 return true;
end; $$;
revoke all on function public.admin_v25_finish_canary(bigint,boolean,text) from public,anon,authenticated;
grant execute on function public.admin_v25_finish_canary(bigint,boolean,text) to authenticated;

create or replace function public.admin_v25_canary_dashboard()
returns table(run_id bigint,run_key text,status text,started_at timestamptz,finished_at timestamptz,checks_total bigint,checks_failed bigint)
language sql stable security definer set search_path=public as $$
 select r.id,r.run_key,r.status,r.started_at,r.finished_at,count(c.id),count(*) filter(where c.status='fail')
 from public.v25_canary_runs r left join public.v25_canary_checks c on c.run_id=r.id
 where public.is_admin() group by r.id order by r.id desc limit 20;
$$;
revoke all on function public.admin_v25_canary_dashboard() from public,anon;
grant execute on function public.admin_v25_canary_dashboard() to authenticated;

create or replace function public.admin_v25_recent_health_events(p_limit integer default 20)
returns table(id bigint,severity text,source text,event_key text,details text,created_at timestamptz)
language sql stable security definer set search_path=public as $$
 select id,severity,source,event_key,details,created_at from public.v25_health_events where public.is_admin() order by id desc limit greatest(1,least(coalesce(p_limit,20),100));
$$;
revoke all on function public.admin_v25_recent_health_events(integer) from public,anon;
grant execute on function public.admin_v25_recent_health_events(integer) to authenticated;
