-- خدماتي V26 — End-to-End Synthetic Release Test
-- اختبارات محاكاة آمنة: لا تنشئ طلبات أو أموالًا حقيقية ولا تشغّل بوابة الدفع.
create table if not exists public.v26_e2e_runs (
 id bigint generated by default as identity primary key,
 run_key text not null unique,
 status text not null default 'running' check (status in ('running','passed','failed')),
 started_by uuid references auth.users(id),
 started_at timestamptz not null default now(),
 finished_at timestamptz,
 passed_count integer not null default 0,
 failed_count integer not null default 0,
 notes text
);
create table if not exists public.v26_e2e_checks (
 id bigint generated by default as identity primary key,
 run_id bigint not null references public.v26_e2e_runs(id) on delete cascade,
 step_no integer not null,
 check_key text not null,
 status text not null check(status in ('pass','fail','skip')),
 details text,
 created_at timestamptz not null default now(),
 unique(run_id,check_key)
);
alter table public.v26_e2e_runs enable row level security;
alter table public.v26_e2e_checks enable row level security;
drop policy if exists "v26 admin runs" on public.v26_e2e_runs;
drop policy if exists "v26 admin checks" on public.v26_e2e_checks;
create policy "v26 admin runs" on public.v26_e2e_runs for select using(public.is_admin());
create policy "v26 admin checks" on public.v26_e2e_checks for select using(public.is_admin());

create or replace function public.admin_v26_run_e2e()
returns bigint language plpgsql security definer set search_path=public as $$
declare rid bigint; k text:='e2e-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS'); fail_count integer:=0;
 c public.platform_control_v24;
begin
 if not public.is_admin() then raise exception 'غير مصرح'; end if;
 select * into c from public.platform_control_v24 where id=true;
 insert into public.v26_e2e_runs(run_key,started_by) values(k,auth.uid()) returning id into rid;
 -- 1. التشغيل الآمن: لا أموال حقيقية أثناء الاختبار
 insert into public.v26_e2e_checks(run_id,step_no,check_key,status,details) values
 (rid,1,'safe_mode',case when c.id=true and not c.payments_enabled and not c.withdrawals_enabled then 'pass' else 'fail' end,
  case when c.id=true and not c.payments_enabled and not c.withdrawals_enabled then 'الدفع والسحب متوقفان' else 'يجب إيقاف الدفع والسحب' end);
 -- 2. وجود طبقات الطلب والمطابقة والتوزيع
 insert into public.v26_e2e_checks(run_id,step_no,check_key,status,details) values
 (rid,2,'workflow_schema',case when to_regclass('public.workflow_runs') is not null and to_regclass('public.workflow_transitions') is not null then 'pass' else 'fail' end,'workflow_runs / workflow_transitions'),
 (rid,3,'matching_schema',case when to_regclass('public.dispatch_attempts') is not null then 'pass' else 'fail' end,'dispatch_attempts متاحة للتوزيع');
 -- 3. طبقة الدفع والتسوية والرقابة المالية
 insert into public.v26_e2e_checks(run_id,step_no,check_key,status,details) values
 (rid,4,'payment_schema',case when to_regclass('public.payment_orders') is not null and to_regprocedure('public.create_payment_order(bigint,text,text)') is not null then 'pass' else 'fail' end,'payment_orders + create_payment_order(3 args)'),
 (rid,5,'settlement_schema',case when to_regprocedure('public.release_request_payment(bigint)') is not null then 'pass' else 'fail' end,'مسار التسوية موجود'),
 (rid,6,'financial_ledger',case when to_regclass('public.commission_ledger') is not null then 'pass' else 'fail' end,'commission_ledger موجود');
 -- 4. منع التكرار وسجل الصحة
 insert into public.v26_e2e_checks(run_id,step_no,check_key,status,details) values
 (rid,7,'idempotency',case when exists(select 1 from information_schema.columns where table_schema='public' and table_name='payment_orders' and column_name='idempotency_key') then 'pass' else 'fail' end,'مفتاح Idempotency موجود'),
 (rid,8,'observability',case when to_regclass('public.v25_health_events') is not null then 'pass' else 'fail' end,'سجل صحة المنصة موجود');
 -- 5. بوابة الإطلاق
 insert into public.v26_e2e_checks(run_id,step_no,check_key,status,details) values
 (rid,9,'launch_gate',case when to_regprocedure('public.admin_v24_launch_gate()') is not null then 'pass' else 'fail' end,'Launch Gate موجود'),
 (rid,10,'admin_security',case when to_regprocedure('public.is_admin()') is not null then 'pass' else 'fail' end,'حارس الإدارة موجود');
 select count(*) filter(where status='fail') into fail_count from public.v26_e2e_checks where run_id=rid;
 update public.v26_e2e_runs set failed_count=fail_count,passed_count=(select count(*) from public.v26_e2e_checks where run_id=rid and status='pass'),status=case when fail_count=0 then 'passed' else 'failed' end,finished_at=now(),notes=case when fail_count=0 then 'Synthetic E2E PASS — لم يتم لمس أموال حقيقية' else 'Synthetic E2E FAIL — راجع الخطوات الفاشلة' end where id=rid;
 return rid;
end; $$;
revoke all on function public.admin_v26_run_e2e() from public,anon,authenticated;
grant execute on function public.admin_v26_run_e2e() to authenticated;

create or replace function public.admin_v26_e2e_dashboard()
returns table(run_id bigint,run_key text,status text,started_at timestamptz,finished_at timestamptz,passed_count integer,failed_count integer,notes text)
language sql stable security definer set search_path=public as $$
 select id,run_key,status,started_at,finished_at,passed_count,failed_count,notes from public.v26_e2e_runs where public.is_admin() order by id desc limit 20;
$$;
revoke all on function public.admin_v26_e2e_dashboard() from public,anon;
grant execute on function public.admin_v26_e2e_dashboard() to authenticated;

create or replace function public.admin_v26_e2e_checks(p_run_id bigint)
returns table(step_no integer,check_key text,status text,details text)
language sql stable security definer set search_path=public as $$
 select step_no,check_key,status,details from public.v26_e2e_checks where run_id=p_run_id and public.is_admin() order by step_no;
$$;
revoke all on function public.admin_v26_e2e_checks(bigint) from public,anon;
grant execute on function public.admin_v26_e2e_checks(bigint) to authenticated;
